// GENERATED by scripts/extract_dgft_annexure.py - do not edit by hand.
// Source: docs/Certificate+of+Origin+Open+API+v1.0.pdf, section 7 (Annexure).
// Every value is a PDF table cell with whitespace collapsed. Rerun the
// script against a new PDF instead of editing this file.

export const DGFT_ANNEXURE_SOURCE = {
  "file": "docs/Certificate+of+Origin+Open+API+v1.0.pdf",
  "sha256": "9227136b3150940b84103ae3e3e9830a0f5976eefbf58655b0b2eee923696ace",
  "rowCounts": {
    "state": 38,
    "district": 698,
    "uom": 37,
    "country": 264,
    "domesticPort": 1000
  }
} as const

// 7.3 Table State - names only; the PDF gives no state codes.
export const STATE_NAMES: readonly string[] = [
  "ANDAMAN AND NICOBAR ISLANDS",
  "ANDHRA PRADESH",
  "ARUNACHAL PRADESH",
  "ASSAM",
  "BIHAR",
  "CHANDIGARH",
  "CHHATTISGARH",
  "DADRA AND NAGAR HAVELI",
  "DAMAN AND DIU",
  "DELHI",
  "Exclusive Economic Zone (EEZ)",
  "GOA",
  "GUJARAT",
  "HARYANA",
  "HIMACHAL PRADESH",
  "JAMMU AND KASHMIR",
  "JHARKHAND",
  "KARNATAKA",
  "KERALA",
  "LADAKH",
  "LAKSHADWEEP",
  "MADHYA PRADESH",
  "MAHARASHTRA",
  "MANIPUR",
  "MEGHALAYA",
  "MIZORAM",
  "NAGALAND",
  "ODISHA",
  "PUDUCHERRY",
  "PUNJAB",
  "RAJASTHAN",
  "SIKKIM",
  "TAMIL NADU",
  "TELANGANA",
  "TRIPURA",
  "UTTAR PRADESH",
  "UTTARAKHAND",
  "WEST BENGAL"
]

// 7.4 Table District - names only, no state column. Names that repeat
// (the same district name in two states) are listed once.
export const DISTRICT_NAMES: readonly string[] = [
  "NORTH AND MIDDLE ANDAMAN",
  "NICOBARS",
  "SOUTH ANDAMAN",
  "WEST GODAVARI",
  "VIZIANAGARAM",
  "VISAKHAPATANAM",
  "SRIKAKULAM",
  "PRAKASAM",
  "SPSR NELLORE",
  "KURNOOL",
  "KRISHNA",
  "GUNTUR",
  "EAST GODAVARI",
  "CHITTOOR",
  "ANANTAPUR",
  "WEST SIANG",
  "WEST KAMENG",
  "UPPER SUBANSIRI",
  "UPPER SIANG",
  "TIRAP",
  "TAWANG",
  "PAPUM PARE",
  "LOWER SUBANSIRI",
  "LOHIT",
  "KURUNG KUMEY",
  "EAST SIANG",
  "EAST KAMENG",
  "DIBANG VALLEY",
  "CHANGLANG",
  "KAMRUP METROPOLITAN",
  "UDALGURI",
  "BAKSA",
  "TINSUKIA",
  "SONITPUR",
  "SIVASAGAR",
  "NALBARI",
  "NAGAON",
  "MARIGAON",
  "LAKHIMPUR",
  "KOKRAJHAR",
  "KARIMGANJ",
  "KARBI ANGLONG",
  "KAMRUP",
  "JORHAT",
  "HAILAKANDI",
  "GOLAGHAT",
  "GOALPARA",
  "DIBRUGARH",
  "DHUBRI",
  "DHEMAJI",
  "DARRANG",
  "CACHAR",
  "BONGAIGAON",
  "BARPETA",
  "ARWAL",
  "VAISHALI",
  "SUPAUL",
  "SIWAN",
  "SITAMARHI",
  "SHEOHAR",
  "SHEIKHPURA",
  "SARAN",
  "SAMASTIPUR",
  "SAHARSA",
  "ROHTAS",
  "PURNIA",
  "EAST CHAMPARAN",
  "PATNA",
  "PASHCHIM CHAMPARAN",
  "NAWADA",
  "NALANDA",
  "MUZAFFARPUR",
  "MUNGER",
  "MADHUBANI",
  "MADHEPURA",
  "LAKHISARAI",
  "KISHANGANJ",
  "KHAGARIA",
  "KATIHAR",
  "KAIMUR (BHABUA)",
  "JEHANABAD",
  "JAMUI",
  "GOPALGANJ",
  "GAYA",
  "DARBHANGA",
  "BUXAR",
  "BHOJPUR",
  "BHAGALPUR",
  "BEGUSARAI",
  "BANKA",
  "AURANGABAD",
  "ARARIA",
  "CHANDIGARH",
  "BEMETARA",
  "BALRAMPUR",
  "SURAJPUR",
  "MUNGELI",
  "BALOD",
  "GARIYABAND",
  "BALODA BAZAR",
  "NARAYANPUR",
  "BIJAPUR",
  "SURGUJA",
  "RAJNANDGAON",
  "RAIPUR",
  "RAIGARH",
  "MAHASAMUND",
  "KORIYA",
  "KORBA",
  "KABIRDHAM",
  "KANKER",
  "JASHPUR",
  "JANJGIR-CHAMPA",
  "DURG",
  "DHAMTARI",
  "DANTEWADA",
  "BILASPUR",
  "BASTAR",
  "DADRA AND NAGAR HAVELI",
  "DIU",
  "DAMAN",
  "WEST DELHI",
  "SOUTH WEST DELHI",
  "SOUTH DELHI",
  "NORTH WEST DELHI",
  "NORTH EAST DELHI",
  "NORTH DELHI",
  "NEW DELHI",
  "EAST DELHI",
  "CENTRAL DELHI",
  "SOUTH GOA",
  "NORTH GOA",
  "TAPI",
  "VALSAD",
  "VADODARA",
  "SURENDRA NAGAR",
  "SURAT",
  "SABAR KANTHA",
  "RAJKOT",
  "PORBANDAR",
  "PATAN",
  "PANCH MAHALS",
  "NAVSARI",
  "NARMADA",
  "MAHESANA",
  "KHEDA",
  "KACHCHH",
  "JUNAGADH",
  "JAMNAGAR",
  "GANDHINAGAR",
  "DOHAD",
  "DANG",
  "BHAVNAGAR",
  "BHARUCH",
  "BANAS KANTHA",
  "ANAND",
  "AMRELI",
  "AHMEDABAD",
  "NUH (Mewat)",
  "YAMUNANAGAR",
  "SONIPAT",
  "SIRSA",
  "ROHTAK",
  "REWARI",
  "PANIPAT",
  "PANCHKULA",
  "MAHENDRAGARH",
  "KURUKSHETRA",
  "KARNAL",
  "KAITHAL",
  "JIND",
  "JHAJJAR",
  "HISAR",
  "GURUGRAM",
  "FATEHABAD",
  "FARIDABAD",
  "BHIWANI",
  "AMBALA",
  "UNA",
  "SOLAN",
  "SIRMAUR",
  "SHIMLA",
  "MANDI",
  "LAHUL AND SPITI",
  "KULLU",
  "KINNAUR",
  "KANGRA",
  "HAMIRPUR",
  "CHAMBA",
  "REASI",
  "GANDERBAL",
  "SHOPIAN",
  "SAMBA",
  "BANDIPORA",
  "KULGAM",
  "RAMBAN",
  "UDHAMPUR",
  "SRINAGAR",
  "RAJAURI",
  "PULWAMA",
  "POONCH",
  "KUPWARA",
  "KATHUA",
  "JAMMU",
  "DODA",
  "BARAMULLA",
  "BADGAM",
  "ANANTNAG",
  "RAMGARH",
  "KHUNTI",
  "WEST SINGHBHUM",
  "SIMDEGA",
  "SARAIKELA KHARSAWAN",
  "SAHEBGANJ",
  "RANCHI",
  "PALAMU",
  "PAKUR",
  "LOHARDAGA",
  "LATEHAR",
  "KODERMA",
  "JAMTARA",
  "HAZARIBAGH",
  "GUMLA",
  "GODDA",
  "GIRIDIH",
  "GARHWA",
  "EAST SINGHBUM",
  "DUMKA",
  "DHANBAD",
  "DEOGHAR",
  "CHATRA",
  "BOKARO",
  "YADGIR",
  "RAMANAGARA",
  "CHIKBALLAPUR",
  "UTTAR KANNAD",
  "UDUPI",
  "TUMAKURU",
  "SHIVAMOGGA",
  "RAICHUR",
  "MYSURU",
  "MANDYA",
  "KOPPAL",
  "KOLAR",
  "KODAGU",
  "HAVERI",
  "HASSAN",
  "KALABURAGI",
  "GADAG",
  "DHARWAD",
  "DAVANGERE",
  "DAKSHINA KANNADA",
  "CHITRADURGA",
  "CHIKKAMAGALURU",
  "CHAMARAJANAGAR",
  "BIDAR",
  "BALLARI",
  "BELAGAVI",
  "BENGALURU RURAL",
  "BENGALURU URBAN",
  "BAGALKOT",
  "WAYANAD",
  "THRISSUR",
  "THIRUVANANTHAPURAM",
  "PATHANAMTHITTA",
  "PALAKKAD",
  "MALAPPURAM",
  "KOZHIKODE",
  "KOTTAYAM",
  "KOLLAM",
  "KASARAGOD",
  "KANNUR",
  "IDUKKI",
  "ERNAKULAM",
  "ALAPPUZHA",
  "LAKSHADWEEP DISTRICT",
  "ALIRAJPUR",
  "SINGRAULI",
  "VIDISHA",
  "UMARIA",
  "UJJAIN",
  "TIKAMGARH",
  "SIDHI",
  "SHIVPURI",
  "SHAJAPUR",
  "SHAHDOL",
  "SEONI",
  "SEHORE",
  "SATNA",
  "SAGAR",
  "REWA",
  "RATLAM",
  "RAJGARH",
  "RAISEN",
  "PANNA",
  "NEEMUCH",
  "NARSINGHPUR",
  "MORENA",
  "MANDSAUR",
  "MANDLA",
  "KHARGONE",
  "KATNI",
  "JHABUA",
  "JABALPUR",
  "INDORE",
  "HOSHANGABAD",
  "HARDA",
  "GWALIOR",
  "GUNA",
  "DINDORI",
  "DHAR",
  "DEWAS",
  "DATIA",
  "DAMOH",
  "CHHINDWARA",
  "CHHATARPUR",
  "BURHANPUR",
  "BHOPAL",
  "BHIND",
  "BETUL",
  "BARWANI",
  "BALAGHAT",
  "ASHOKNAGAR",
  "ANUPPUR",
  "PALGHAR",
  "YAVATMAL",
  "WASHIM",
  "WARDHA",
  "THANE",
  "SOLAPUR",
  "SINDHUDURG",
  "SATARA",
  "SANGLI",
  "RATNAGIRI",
  "RAIGAD",
  "PUNE",
  "PARBHANI",
  "OSMANABAD",
  "NASHIK",
  "NANDURBAR",
  "NANDED",
  "NAGPUR",
  "MUMBAI SUBURBAN",
  "MUMBAI",
  "LATUR",
  "KOLHAPUR",
  "JALNA",
  "JALGAON",
  "HINGOLI",
  "GONDIA",
  "GADCHIROLI",
  "DHULE",
  "CHANDRAPUR",
  "BULDHANA",
  "BHANDARA",
  "BEED",
  "AMRAVATI",
  "AKOLA",
  "AHMED NAGAR",
  "UKHRUL",
  "THOUBAL",
  "TAMENGLONG",
  "SENAPATI",
  "IMPHAL WEST",
  "IMPHAL EAST",
  "CHURACHANDPUR",
  "CHANDEL",
  "BISHNUPUR",
  "EAST JAINTIA HILLS",
  "WEST KHASI HILLS",
  "WEST GARO HILLS",
  "SOUTH GARO HILLS",
  "RI BHOI",
  "EAST KHASI HILLS",
  "EAST GARO HILLS",
  "SERCHHIP",
  "SAIHA",
  "MAMIT",
  "LUNGLEI",
  "LAWNGTLAI",
  "KOLASIB",
  "CHAMPHAI",
  "AIZAWL",
  "LONGLENG",
  "KIPHIRE",
  "PEREN",
  "ZUNHEBOTO",
  "WOKHA",
  "TUENSANG",
  "PHEK",
  "MON",
  "MOKOKCHUNG",
  "KOHIMA",
  "DIMAPUR",
  "SUNDARGARH",
  "SONEPUR",
  "SAMBALPUR",
  "RAYAGADA",
  "PURI",
  "NUAPADA",
  "NAYAGARH",
  "NABARANGPUR",
  "MAYURBHANJ",
  "MALKANGIRI",
  "KORAPUT",
  "KHORDHA",
  "KENDUJHAR",
  "KENDRAPARA",
  "KANDHAMAL",
  "KALAHANDI",
  "JHARSUGUDA",
  "JAJAPUR",
  "JAGATSINGHPUR",
  "GANJAM",
  "GAJAPATI",
  "DHENKANAL",
  "DEOGARH",
  "CUTTACK",
  "BOUDH",
  "BHADRAK",
  "BARGARH",
  "BALESHWAR",
  "BALANGIR",
  "ANUGUL",
  "PONDICHERRY",
  "MAHE",
  "KARAIKAL",
  "PATHANKOT",
  "FAZILKA",
  "TARN TARAN",
  "S.A.S NAGAR",
  "SANGRUR",
  "RUPNAGAR",
  "PATIALA",
  "NAWANSHAHR",
  "SRI MUKTSAR SAHIB",
  "MOGA",
  "MANSA",
  "LUDHIANA",
  "KAPURTHALA",
  "JALANDHAR",
  "HOSHIARPUR",
  "GURDASPUR",
  "FIROZPUR",
  "FATEHGARH SAHIB",
  "FARIDKOT",
  "BATHINDA",
  "AMRITSAR",
  "PRATAPGARH",
  "UDAIPUR",
  "TONK",
  "SIROHI",
  "SIKAR",
  "SAWAI MADHOPUR",
  "RAJSAMAND",
  "PALI",
  "NAGAUR",
  "KOTA",
  "KARAULI",
  "JODHPUR",
  "JHUNJHUNU",
  "JHALAWAR",
  "JALORE",
  "JAISALMER",
  "JAIPUR",
  "HANUMANGARH",
  "GANGANAGAR",
  "DUNGARPUR",
  "DHOLPUR",
  "DAUSA",
  "CHURU",
  "CHITTORGARH",
  "BUNDI",
  "BIKANER",
  "BHILWARA",
  "BHARATPUR",
  "BARMER",
  "BARAN",
  "BANSWARA",
  "ALWAR",
  "AJMER",
  "WEST DISTRICT",
  "SOUTH DISTRICT",
  "NORTH DISTRICT",
  "EAST DISTRICT",
  "TIRUPPUR",
  "ARIYALUR",
  "VIRUDHUNAGAR",
  "VILLUPURAM",
  "VELLORE",
  "TUTICORIN",
  "TIRUVANNAMALAI",
  "TIRUNELVELI",
  "TIRUCHIRAPPALLI",
  "THIRUVARUR",
  "THIRUVALLUR",
  "THENI",
  "THE NILGIRIS",
  "THANJAVUR",
  "SIVAGANGA",
  "SALEM",
  "RAMANATHAPURAM",
  "PUDUKKOTTAI",
  "PERAMBALUR",
  "NAMAKKAL",
  "NAGAPATTINAM",
  "MADURAI",
  "KRISHNAGIRI",
  "KARUR",
  "KANYAKUMARI",
  "KANCHIPURAM",
  "ERODE",
  "DINDIGUL",
  "DHARMAPURI",
  "CUDDALORE",
  "COIMBATORE",
  "CHENNAI",
  "WARANGAL",
  "RANGAREDDY",
  "NIZAMABAD",
  "NALGONDA",
  "MEDAK",
  "MAHABUB NAGAR",
  "KHAMMAM",
  "KARIM NAGAR",
  "HYDERABAD",
  "ADILABAD",
  "GOMATI",
  "SEPAHIJALA",
  "WEST TRIPURA",
  "SOUTH TRIPURA",
  "NORTH TRIPURA",
  "DHALAI",
  "HAPUR",
  "SAMBHAL",
  "AMETHI",
  "VARANASI",
  "UNNAO",
  "SULTANPUR",
  "SONBHADRA",
  "SITAPUR",
  "SIDDHARTH NAGAR",
  "SHRAVASTI",
  "SHAHJAHANPUR",
  "SANT KABEER NAGAR",
  "SAHARANPUR",
  "RAMPUR",
  "RAE BARELI",
  "PILIBHIT",
  "MUZAFFARNAGAR",
  "MORADABAD",
  "MIRZAPUR",
  "MEERUT",
  "MAU",
  "MATHURA",
  "MAINPURI",
  "MAHOBA",
  "MAHARAJGANJ",
  "HATHRAS",
  "LUCKNOW",
  "LALITPUR",
  "KUSHI NAGAR",
  "KHERI",
  "KANPUR NAGAR",
  "KANPUR DEHAT",
  "KANNAUJ",
  "AMROHA",
  "JHANSI",
  "JAUNPUR",
  "JALAUN",
  "HARDOI",
  "GORAKHPUR",
  "GONDA",
  "GHAZIPUR",
  "GHAZIABAD",
  "GAUTAM BUDDHA NAGAR",
  "FIROZABAD",
  "FATEHPUR",
  "FARRUKHABAD",
  "FAIZABAD",
  "ETAWAH",
  "ETAH",
  "DEORIA",
  "CHITRAKOOT",
  "CHANDAULI",
  "BULANDSHAHR",
  "BUDAUN",
  "BIJNOR",
  "BASTI",
  "BAREILLY",
  "BARABANKI",
  "BANDA",
  "BALLIA",
  "BAHRAICH",
  "BAGHPAT",
  "AZAMGARH",
  "AURAIYA",
  "AMBEDKAR NAGAR",
  "PRAYAGRAJ",
  "ALIGARH",
  "AGRA",
  "UTTAR KASHI",
  "UDAM SINGH NAGAR",
  "TEHRI GARHWAL",
  "RUDRA PRAYAG",
  "PITHORAGARH",
  "PAURI GARHWAL",
  "NAINITAL",
  "HARIDWAR",
  "DEHRADUN",
  "CHAMPAWAT",
  "CHAMOLI",
  "BAGESHWAR",
  "ALMORA",
  "PURULIA",
  "NADIA",
  "MURSHIDABAD",
  "MEDINIPUR WEST",
  "MEDINIPUR EAST",
  "MALDAH",
  "KOLKATA",
  "JALPAIGURI",
  "HOWRAH",
  "HOOGHLY",
  "DINAJPUR UTTAR",
  "DINAJPUR DAKSHIN",
  "DARJEELING",
  "COOCHBEHAR",
  "BIRBHUM",
  "BARDHAMAN",
  "BANKURA",
  "24 PARAGANAS SOUTH",
  "24 PARAGANAS NORTH",
  "Y.S.R.",
  "SHAHDARA",
  "ARVALLI",
  "BOTAD",
  "DEVBHUMI DWARKA",
  "GIR SOMNATH",
  "MAHISAGAR",
  "MORBI",
  "BIJAPURKAR",
  "AGAR MALWA",
  "JAINTIA HILLS",
  "Bhadradri Kothagudem",
  "JAGTIAL",
  "JANGAON",
  "kamareddy",
  "Mahabubabad",
  "Mancherial",
  "Nagar kurnool",
  "Nirmal",
  "Peddapalli",
  "Rajanna Sircilla",
  "Sangareddy",
  "Siddipet",
  "Suryapet",
  "Vikarabad",
  "Wanaparthy",
  "SANT RAVIDAS NAGAR",
  "Exclusive Economic Zone (EEZ)",
  "LEH",
  "KARGIL",
  "YANAM",
  "KALLAKURICHI",
  "TIRUPATHUR",
  "KHANDWA (EAST NIMAR)",
  "ALIPURDUAR",
  "CHENGALPATTU",
  "YADADRI BHUVANAGIRI",
  "VIJAYNAGAR",
  "Vijayapura",
  "Medchal Malkajgiri",
  "KUMURAM BHEEM ASIFABAD",
  "HANUMAKONDA",
  "JAYASHANKAR BHUPALAPALLY",
  "Mulugu",
  "Narayanpet",
  "JOGULAMBA GADWAL",
  "Sri Sathya Sai",
  "Annamayya",
  "TIRUPATI",
  "Nandyal",
  "NTR",
  "Eluru",
  "Bapatla",
  "Palnadu",
  "Anakapalli",
  "Alluri Sitharama Raju",
  "Parvathipuram Manyam",
  "Kakinada",
  "Konaseema"
]

// 7.9 UOM Table - "Code(input)" and "Value".
export const UOM_ROWS: readonly { code: string; name: string }[] = [
  {
    "code": "YDS",
    "name": "YARDS (YDS)"
  },
  {
    "code": "VLS",
    "name": "VIALS (VLS)"
  },
  {
    "code": "UNT",
    "name": "UNITS (UNT)"
  },
  {
    "code": "THD",
    "name": "THOUSANDS (THD)"
  },
  {
    "code": "TKW",
    "name": "THOUSAN KILO WATT HR (TKW)"
  },
  {
    "code": "TBS",
    "name": "TABLETS (TBS)"
  },
  {
    "code": "SQY",
    "name": "SQUARE YARDS (SQY)"
  },
  {
    "code": "SQM",
    "name": "SQUARE METER (SQM)"
  },
  {
    "code": "SQI",
    "name": "SQUARE INCHES (SQI)"
  },
  {
    "code": "SQF",
    "name": "SQUARE FEET (SQF)"
  },
  {
    "code": "SET",
    "name": "SETS (SET)"
  },
  {
    "code": "QTL",
    "name": "QUINTAL (QTL)"
  },
  {
    "code": "LBS",
    "name": "POUNDS (LBS)"
  },
  {
    "code": "PCS",
    "name": "PIECES (PCS)"
  },
  {
    "code": "PRS",
    "name": "PAIRS (PRS)"
  },
  {
    "code": "NOS",
    "name": "NUMBERS (NOS)"
  },
  {
    "code": "MGS",
    "name": "MILLI GRAMS (MGS)"
  },
  {
    "code": "MTS",
    "name": "METRIC TON (MTS)"
  },
  {
    "code": "MTR",
    "name": "METER (MTR)"
  },
  {
    "code": "LTR",
    "name": "LITERS (LTR)"
  },
  {
    "code": "KME",
    "name": "KILOMETERS (KME)"
  },
  {
    "code": "KLR",
    "name": "KILOLITER (KLR)"
  },
  {
    "code": "KGS",
    "name": "KILOGRAMS (KGS)"
  },
  {
    "code": "KGA",
    "name": "KILOGRAM ACTIVITY (KGA)"
  },
  {
    "code": "KWH",
    "name": "KILO WATT HOUR (KWH)"
  },
  {
    "code": "INC",
    "name": "INCHES (INC)"
  },
  {
    "code": "HKS",
    "name": "HANKS (HKS)"
  },
  {
    "code": "GYD",
    "name": "GROSS YARDS (GYD)"
  },
  {
    "code": "GRS",
    "name": "GROSS (GRS)"
  },
  {
    "code": "GIF",
    "name": "GRM FISSILE ISOTOPE (GIF)"
  },
  {
    "code": "GMS",
    "name": "GRAMS (GMS)"
  },
  {
    "code": "FTS",
    "name": "FEET (FTS)"
  },
  {
    "code": "DOZ",
    "name": "DOZEN (DOZ)"
  },
  {
    "code": "CBM",
    "name": "CUBIC METER (CBM)"
  },
  {
    "code": "CCM",
    "name": "CUBIC CENTIMETER (CCM)"
  },
  {
    "code": "CMS",
    "name": "CENTIMETER (CMS)"
  },
  {
    "code": "CTM",
    "name": "CARAT (CTM)"
  }
]

// 7.10 Table Country - names only; exact repeats at the end of the table
// are listed once.
export const COUNTRY_NAMES: readonly string[] = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua And Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia And Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Cook Islands",
  "Costa Rica",
  "Ivory Coast (Cote D'Ivoire)",
  "Croatia",
  "Cuba",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard And Mc Donald Islands",
  "Holy See (Vatican City State)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran (Islamic Republic Of)",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea (Democratic People's Republic Of)",
  "Republic Of Korea",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "North Macedonia",
  "Madagascar",
  "Malawi",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands (Malvinas)",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guinea",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Saint Kitts And Nevis",
  "Saint Lucia",
  "Saint Vincent And The Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome And Principe",
  "Saudi Arabia",
  "Senegal",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia (Slovak Republic)",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia And South S.S.",
  "Spain",
  "Sri Lanka",
  "St. Helena",
  "St. Pierre And Miquelon",
  "Sudan",
  "Suriname",
  "Svalbard And Jan Mayen Islands",
  "Swaziland",
  "Sweden",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia, Federated States Of",
  "Moldova, Republic Of",
  "Monaco",
  "Mongolia",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan",
  "Tajikistan",
  "Tanzania, United Republic Of",
  "Thailand",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad And Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks And Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States Of America",
  "U.S. Minor Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "VIETNAM",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
  "Wallis And Futuna Islands",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Timor Leste",
  "Serbia",
  "Montenegro",
  "Canary Island",
  "Congo P Rep",
  "Congo D Rep",
  "Saharwi A Dmrp",
  "Palestine State",
  "South Sudan",
  "Kosovo",
  "Sint Maarten (Dutch Part)",
  "Saint Martin (French Part)",
  "Jersey",
  "Isle Of Man",
  "Guernsey",
  "Curaçao",
  "Bonaire, Sint Eustatius And Saba",
  "Saint Barthélemy",
  "Åland Islands"
]

// 7.11 Table Domestic Port - "Value" and "Code (Input)", every row as
// printed, including the few that are not port codes.
export const DOMESTIC_PORT_ROWS: readonly { name: string; code: string }[] = [
  {
    "name": "Car-Nicobar3",
    "code": "INCNB1"
  },
  {
    "name": "Cornwallis",
    "code": "INCRN1"
  },
  {
    "name": "Mayabandar",
    "code": "INMYB1"
  },
  {
    "name": "Elphinstone Harbour",
    "code": "INESH1"
  },
  {
    "name": "Ranghat Bay",
    "code": "INRGT1"
  },
  {
    "name": "Meadows",
    "code": "INMDW1"
  },
  {
    "name": "ACC AHMEDABAD OLD AIRPORT, SAHIBAUG AHMEDABAD 12",
    "code": "INAMD4"
  },
  {
    "name": "Nancowrie",
    "code": "INNAN1"
  },
  {
    "name": "SEA PORT-PORT BLAIR, ANDAMAN & NICOBAR ISLANDS.",
    "code": "INIXZ1"
  },
  {
    "name": "Port Blair",
    "code": "INIXZ4"
  },
  {
    "name": "Navaspur",
    "code": "INNVP1"
  },
  {
    "name": "VISHAKHAPATNAM SPECIAL ECONOMIC ZONE VISHKHAPATNAM",
    "code": "INVTZ6"
  },
  {
    "name": "Vadarevu",
    "code": "INVRU1"
  },
  {
    "name": "Karedu",
    "code": "INKDD6"
  },
  {
    "name": "AIR CARGO COMPLEX VISAKHAPATNAM",
    "code": "INVTZ4"
  },
  {
    "name": "Anaparthi",
    "code": "INAPT6"
  },
  {
    "name": "Chirala",
    "code": "INCLX6"
  },
  {
    "name": "Masulipatnam",
    "code": "INMAP1"
  },
  {
    "name": "ICES, KRISHNAPATNAM PORT, NELLORE-524003",
    "code": "INKRI1"
  },
  {
    "name": "Nampong",
    "code": "INNPGB"
  },
  {
    "name": "LAND CUSTOMS STATION, BAKSA-BTAD, DARRANGA, ASSAM",
    "code": "INDRGB"
  },
  {
    "name": "GUWAHATI AIR CARGO, BORJHAR, ASSAM",
    "code": "INGAU4"
  },
  {
    "name": "Gauhati Steamerghat",
    "code": "INGHWB"
  },
  {
    "name": "Dhubri Steamerghat",
    "code": "INDHBB"
  },
  {
    "name": "Gitaldah road",
    "code": "INGTGB"
  },
  {
    "name": "Golakganj Raiiway Station",
    "code": "INGKJ2"
  },
  {
    "name": "LCS HATISAR, RUNIKHATA, ASSAM - 783375",
    "code": "INHTSB"
  },
  {
    "name": "LAND CUSTOMS STATION- KUNAULI, BIHAR",
    "code": "INKNLB"
  },
  {
    "name": "Kathihar",
    "code": "INKTRB"
  },
  {
    "name": "LCS JAYANAGAR, DIST-MADHUBANI, BIHAR",
    "code": "INJAYB"
  },
  {
    "name": "LAND CUSTOMS STATION, BHITAMORE, BIHAR",
    "code": "INBTMB"
  },
  {
    "name": "LAND CUSTOMS STATION, BAIRGANIA, DIST. SITAMARHI,",
    "code": "INBGUB"
  },
  {
    "name": "LCS BHIMNAGAR, DIST-SUPUAL, BIHAR",
    "code": "INBNRB"
  },
  {
    "name": "Gaya",
    "code": "INGAY4"
  },
  {
    "name": "Patna",
    "code": "INPAT4"
  },
  {
    "name": "ICD RAIPUR NEAR GOODS-SHED KAPA RAIPUR 492009",
    "code": "INRAI6"
  },
  {
    "name": "Daman & Diu",
    "code": "INDAM1"
  },
  {
    "name": "Sinbhour Port",
    "code": "INSHP1"
  },
  {
    "name": "Pellet Plant Jetty at Shiroda",
    "code": "INPPJ1"
  },
  {
    "name": "Panjim",
    "code": "INPNJ1"
  },
  {
    "name": "Chapora",
    "code": "INCHR1"
  },
  {
    "name": "Betul",
    "code": "INBET1"
  },
  {
    "name": "LCS KARIMGANJ STEAMERGHAT & FERRY",
    "code": "INKGJB"
  },
  {
    "name": "LCS SUTARKANDI, KARIMGANJ - ASSAM - 788712",
    "code": "INSTRB"
  },
  {
    "name": "Silcher Steamerghat",
    "code": "INSLRB"
  },
  {
    "name": "Silcher R.M.S. Office",
    "code": "INSLR2"
  },
  {
    "name": "Phulbari",
    "code": "INPHBB"
  },
  {
    "name": "Neamati steamer Ghat",
    "code": "INNMTB"
  },
  {
    "name": "LAND CUSTOMS STATION, MANU",
    "code": "INMNUB"
  },
  {
    "name": "Ghogha",
    "code": "INGHA1"
  },
  {
    "name": "LCS MANKACHAR, DISTRICT MANKACHAR - 783131",
    "code": "INMKCB"
  },
  {
    "name": "Mahisashan Railway Station",
    "code": "INMHN2"
  },
  {
    "name": "Latu Bazar",
    "code": "INLTBB"
  },
  {
    "name": "Ultapani",
    "code": "INULPB"
  },
  {
    "name": "Tezpur Steamerghat",
    "code": "INTJPB"
  },
  {
    "name": "Karimganj Railway Station",
    "code": "INKXJ2"
  },
  {
    "name": "HALDIBARI RAILWAY STATION, COOCHBEHAR, WEST BENGAL",
    "code": "INHLD2"
  },
  {
    "name": "LCS GOLAKGANJ, ASSAM - 783334",
    "code": "INGKJB"
  },
  {
    "name": "CONCOR, ICD AMINGAON, GUWAHATI - 781031",
    "code": "INAMG6"
  },
  {
    "name": "ICD WHITEFIELD PLANTATIONS, HOSKOTE, BANGALORE",
    "code": "INWFD6"
  },
  {
    "name": "ACC BANGALORE BENGALURU INTERNATIONAL AIRPORT",
    "code": "INBLR4"
  },
  {
    "name": "Rexaul",
    "code": "INRXL8"
  },
  {
    "name": "LAND CUSTOMS STATION, GALGALIA,BIHAR",
    "code": "INGALB"
  },
  {
    "name": "LCS JOGBANI, DIST: ARARIA, BIHAR",
    "code": "INJBNB"
  },
  {
    "name": "LAND CUSTOMS STATION-SONBARSA, SITAMARHI, BIHAR",
    "code": "INSNBB"
  },
  {
    "name": "LCS RAXAUL, DIST: EAST CHAPARAN, BIHAR",
    "code": "INRXLB"
  },
  {
    "name": "Koteshwar",
    "code": "INKTW1"
  },
  {
    "name": "Kotda",
    "code": "INKTD1"
  },
  {
    "name": "ACC MEENAMBAKKAM, CHENNAI, TAMIL NADU - 600027",
    "code": "INMAA4"
  },
  {
    "name": "CUSTOMS HOUSE 60,RAJAJISALAI,CHENNAI-600001",
    "code": "INMAA1"
  },
  {
    "name": "Umarsadi",
    "code": "INUMR1"
  },
  {
    "name": "T ankari",
    "code": "INTNK1"
  },
  {
    "name": "Beyt",
    "code": "INBYT1"
  },
  {
    "name": "Adalaj",
    "code": "INADA6"
  },
  {
    "name": "BHAVNAGAR PORT, PARAMAL CHOWK, BHAVNAGAR, GUJARAT",
    "code": "INBHU1"
  },
  {
    "name": "COCHIN CUSTOM HOUSE WILLINGDON ISLAND COCHIN682009",
    "code": "INCOK1"
  },
  {
    "name": "Div",
    "code": "INDIV1"
  },
  {
    "name": "Umbergoan",
    "code": "INUMB1"
  },
  {
    "name": "TUNA PORT, KANDLA, GUJARAT",
    "code": "INTUN1"
  },
  {
    "name": "Talaja",
    "code": "INTJA1"
  },
  {
    "name": "ICD VERNA, MARGOA, GOA",
    "code": "INMDG6"
  },
  {
    "name": "GOA AIR CARGO COMPLEX, SADA COMPLEX, MARMAGOA",
    "code": "INGOI4"
  },
  {
    "name": "PANAJI PORT, PANAJI, GOA",
    "code": "INPAN1"
  },
  {
    "name": "BEDI PORT JAMNAGAR GUJRAT",
    "code": "INBED1"
  },
  {
    "name": "Bhagwa",
    "code": "INBGW1"
  },
  {
    "name": "KODINAR PORT, MULDWARKA, GUJARAT",
    "code": "INKDN1"
  },
  {
    "name": "Kavi",
    "code": "INKVI1"
  },
  {
    "name": "ICD VALVADA NH8 TALUKA:UMBERGAON VALSAD GUJARAT",
    "code": "INVPI6"
  },
  {
    "name": "SURAT SPECIAL ECONOMIC ZONE, SACHIN, SURAT, GUJ.",
    "code": "INSTV6"
  },
  {
    "name": "Gandhidham",
    "code": "INGIN6"
  },
  {
    "name": "Dwarka (Rupen)",
    "code": "INDRK1"
  },
  {
    "name": "Dholera",
    "code": "INDHR1"
  },
  {
    "name": "AIR CARGO COMPLEX, SAHAR, ANDHERI(E) MUMBAI 400099",
    "code": "INBOM4"
  },
  {
    "name": "NEW CUSTOM HOUSE, BALLARD ESTATE, MUMBAI - 400038",
    "code": "INBOM1"
  },
  {
    "name": "Cambay",
    "code": "INCMB1"
  },
  {
    "name": "Bulsar",
    "code": "INBSR1"
  },
  {
    "name": "Bilimora",
    "code": "INBLM1"
  },
  {
    "name": "Valvada ICD",
    "code": "INVAL6"
  },
  {
    "name": "Sinbhour",
    "code": "INSBH1"
  },
  {
    "name": "Simor",
    "code": "INSMR1"
  },
  {
    "name": "Rajpara",
    "code": "INRJP1"
  },
  {
    "name": "Onjal",
    "code": "INONJ1"
  },
  {
    "name": "OLD MUNDRA PORT, MUNDRA, GUJARAT",
    "code": "INOMU1"
  },
  {
    "name": "Navabunder",
    "code": "INNVB1"
  },
  {
    "name": "Metwad",
    "code": "INMTW1"
  },
  {
    "name": "JAKHAU PORT, MUNDRA, GUJARAT",
    "code": "INJAK1"
  },
  {
    "name": "Gogha",
    "code": "INGGA1"
  },
  {
    "name": "DAHEJ PORT CUSTOM HOUSE DIST: BAROACH GUJARAT",
    "code": "INDAH1"
  },
  {
    "name": "Broach",
    "code": "INBRH1"
  },
  {
    "name": "ICD ANKLESHWAR OPP ONGC TNSHIP OLD NH8 ANKLESHWAR",
    "code": "INAKV6"
  },
  {
    "name": "Vadodara - Chhani",
    "code": "INCHN6"
  },
  {
    "name": "ICD GARHI HARSARU, SRI MARUTHI NAGAR, GURGAON",
    "code": "INGHR6"
  },
  {
    "name": "ICD REWARI, REWARI HARYANA",
    "code": "INREA6"
  },
  {
    "name": "ICD PATLI, GURGAON, HARYANA",
    "code": "INPTL6"
  },
  {
    "name": "ICD BALAGENCYHGARH, SECTOR 59, FARIDABAD, HARYANA",
    "code": "INFBD6"
  },
  {
    "name": "Kundli",
    "code": "INNUR6"
  },
  {
    "name": "ICD PANIPAT, BABARPUR RAILWAY STATION, PANIPAT",
    "code": "INPNP6"
  },
  {
    "name": "SRINAGAR AIR CARGO, SRINAGAR, JAMMU AND KASHMIR",
    "code": "INSXR4"
  },
  {
    "name": "SIKKA PORT, CUSTOM HOUSE, SIKKA, JAMNAGAR, GUJARAT",
    "code": "INSIK1"
  },
  {
    "name": "ESSAR BULK TERMINAL, SEAPORT- SALAYA, GUJARAT",
    "code": "INSAL1"
  },
  {
    "name": "Pindhara",
    "code": "INPIN1"
  },
  {
    "name": "PORBANDAR PORT,OPP-CIVIL AIRPORT,PORBANDAR,GUJARAT",
    "code": "INPBD1"
  },
  {
    "name": "OKHA PORT, JAMNAGAR DIST, GUJARAT",
    "code": "INOKH1"
  },
  {
    "name": "NAVLAKHI PORT, GUJARAT",
    "code": "INNAV1"
  },
  {
    "name": "Rajkot",
    "code": "INRAJ6"
  },
  {
    "name": "KARWAR PORT, KARNATAKA.",
    "code": "INKRW1"
  },
  {
    "name": "Honawar",
    "code": "INHWR1"
  },
  {
    "name": "Hangarkatta",
    "code": "INHGT1"
  },
  {
    "name": "Kandla (EPZ/SEZ)",
    "code": "INIXY6"
  },
  {
    "name": "SURAT DIAMOND PARK, GIDC, SACHIN, SURAT-394230",
    "code": "INSAC6"
  },
  {
    "name": "Kapadra(Surat)",
    "code": "INKAP6"
  },
  {
    "name": "ICD DASRATH VADODARA GUJARAT - 391740",
    "code": "INBRC6"
  },
  {
    "name": "FPO, GIRDHAR NAGAR, SHAHIBAUGH,AHMEDABAD 380004",
    "code": "INAMD5"
  },
  {
    "name": "Mandvi",
    "code": "INMDV1"
  },
  {
    "name": "Veraval",
    "code": "INVVA1"
  },
  {
    "name": "Vansi-Borsi",
    "code": "INVSI1"
  },
  {
    "name": "NEW CUSTOM HOUSE, IGI AIRPORT, NEW DELHI - 110037",
    "code": "INDEL4"
  },
  {
    "name": "VADINAR PORT, GUJARAT",
    "code": "INVAD1"
  },
  {
    "name": "Mahuva",
    "code": "INMHA1"
  },
  {
    "name": "Mangrol",
    "code": "INMGR1"
  },
  {
    "name": "Muldwarka",
    "code": "INMDK1"
  },
  {
    "name": "MAGDALLA PORT URMI COMPLEX SANGRAMPURA SURAT",
    "code": "INMDA1"
  },
  {
    "name": "Koka",
    "code": "INKOK1"
  },
  {
    "name": "Jodia",
    "code": "INJDA1"
  },
  {
    "name": "Leapuram",
    "code": "INLPR1"
  },
  {
    "name": "ICD SANATHNAGAR, HYDERABAD, 500018",
    "code": "INSNF6"
  },
  {
    "name": "ACC SHAMSHABAD AIRPORT DIST RANGA REDDY HYDERABAD",
    "code": "INHYD4"
  },
  {
    "name": "Kondiapetnam",
    "code": "INKDP1"
  },
  {
    "name": "Kankudy",
    "code": "INKND1"
  },
  {
    "name": "Cannanore",
    "code": "INCNN1"
  },
  {
    "name": "COCHIN SPECIAL ECONOMIC ZONE, COCHIN",
    "code": "INCOK6"
  },
  {
    "name": "Aroor",
    "code": "INARR6"
  },
  {
    "name": "ACC KOZHIKODE, KARIPUR, KERALA, 673647",
    "code": "INCCJ4"
  },
  {
    "name": "Minicoy Island",
    "code": "INMCI1"
  },
  {
    "name": "Tellichery",
    "code": "INTEL1"
  },
  {
    "name": "VIZHINJAM PORT, KERALA",
    "code": "INVZJ1"
  },
  {
    "name": "ICD SANGANER PLOT NO. SP7 SIA JAIPUR PIN-302020",
    "code": "INJAI6"
  },
  {
    "name": "Bari Brahma",
    "code": "INBBM6"
  },
  {
    "name": "ICD JAMSHEDPUR,NEAR FCI GODOWN,TATANAGAR,JHARKHAND",
    "code": "INIXW6"
  },
  {
    "name": "Jamshedpur (ICD)",
    "code": "INTAT6"
  },
  {
    "name": "ICD DESUR, BELGAUM, KARNATAKA-590014",
    "code": "INDRU6"
  },
  {
    "name": "Coondapur (Ganguly)",
    "code": "INCDP1"
  },
  {
    "name": "Padubidri Minor Port",
    "code": "INPDD1"
  },
  {
    "name": "Bitra Island",
    "code": "INBTR1"
  },
  {
    "name": "Chettat Island",
    "code": "INCTI1"
  },
  {
    "name": "Kavaratti Island",
    "code": "INKVT1"
  },
  {
    "name": "Kadmat lsland",
    "code": "INKDI1"
  },
  {
    "name": "Bhatkal",
    "code": "INBTK1"
  },
  {
    "name": "NEW CUSTOM HOUSE MARMAGOA, GOA PIN-403803",
    "code": "INMRM1"
  },
  {
    "name": "Belekeri",
    "code": "INBKR1"
  },
  {
    "name": "Baindur",
    "code": "INBDR1"
  },
  {
    "name": "Coondapur (Ganguly)",
    "code": "INCOO1"
  },
  {
    "name": "Malpe",
    "code": "INMAL1"
  },
  {
    "name": "ICD HASSAN, KARNATAKA",
    "code": "INHAS6"
  },
  {
    "name": "OLD MANGALORE PORT, MANGALORE, KARNATAKA",
    "code": "INIXE1"
  },
  {
    "name": "Badagara",
    "code": "INBDG1"
  },
  {
    "name": "Kallai",
    "code": "INKAL1"
  },
  {
    "name": "Kasargod",
    "code": "INKSG1"
  },
  {
    "name": "Kovalam",
    "code": "INKVL1"
  },
  {
    "name": "Mahe",
    "code": "INMHE1"
  },
  {
    "name": "Ponnani",
    "code": "INPNN1"
  },
  {
    "name": "Rajakkamangalam",
    "code": "INRKG1"
  },
  {
    "name": "Mallipuram",
    "code": "INMLP1"
  },
  {
    "name": "Thal",
    "code": "INTHL1"
  },
  {
    "name": "Tarapur",
    "code": "INTRP1"
  },
  {
    "name": "Deogad",
    "code": "INDEG1"
  },
  {
    "name": "Daulatabad ICD",
    "code": "INDLB6"
  },
  {
    "name": "Dantiwara",
    "code": "INDTW1"
  },
  {
    "name": "Dahanu",
    "code": "INDHN1"
  },
  {
    "name": "Borya",
    "code": "INBRY1"
  },
  {
    "name": "Borlai - Mandla",
    "code": "INBRM1"
  },
  {
    "name": "ICD CONCOR BHUSAWAL B/H SAYALI HOTEL, BHUSAWAL",
    "code": "INBSL6"
  },
  {
    "name": "Bhiwandi",
    "code": "INBWN1"
  },
  {
    "name": "Belapur",
    "code": "INBLP1"
  },
  {
    "name": "KOCHI AIRPORT NEDUMBASSERY COCHIN KERALA 683111",
    "code": "INCOK4"
  },
  {
    "name": "Neendakara",
    "code": "INNEE1"
  },
  {
    "name": "C.H. Kozikode",
    "code": "INCCJ1"
  },
  {
    "name": "AZHIKKAL PORT, KERALA",
    "code": "INAZK1"
  },
  {
    "name": "Agatti Island",
    "code": "INAGI1"
  },
  {
    "name": "Kiltan Island",
    "code": "INKTI1"
  },
  {
    "name": "Androth Island",
    "code": "INADI1"
  },
  {
    "name": "Harnai",
    "code": "INHRN1"
  },
  {
    "name": "DIGHI PORT,TK SHRIWARDHAN-DIST RAIGAD, MAHARASHTRA",
    "code": "INDIG1"
  },
  {
    "name": "ACC JANORI, JANORI DINDORI, DIST NASIK, PIN-422207",
    "code": "INJNR4"
  },
  {
    "name": "ICD JANORI, JANORI DANDORI DIST: NASIK PIN-422207",
    "code": "INJNR6"
  },
  {
    "name": "ICD TALEGAON A-18 & 18/1 MIDC TALEGAON PUNE 410507",
    "code": "INTLG6"
  },
  {
    "name": "Amini IsTand",
    "code": "INAMI1"
  },
  {
    "name": "ICD, MALANPUR, DIST BHIND, MADHYA PRADESH",
    "code": "INMPR6"
  },
  {
    "name": "M/S PEGASUS ICD, VILL-DHANNAD,INDORE,MP - 453001",
    "code": "INDHA6"
  },
  {
    "name": "ICD MADIDEEP 34-A1 NIA DIST: RAISEN MP 462046",
    "code": "INMDD6"
  },
  {
    "name": "ACC DEVI AHILYABHAI HOLKAR AIRPORT INDORE MP",
    "code": "INIDR4"
  },
  {
    "name": "Malanpur(Gwalior)",
    "code": "INGWL6"
  },
  {
    "name": "CUSTOM HOUSE, PORT AREA, KAKINADA - 533007",
    "code": "INKAK1"
  },
  {
    "name": "Achra",
    "code": "INACH1"
  },
  {
    "name": "Vengurla",
    "code": "INVNG1"
  },
  {
    "name": "Varsava",
    "code": "INVSV1"
  },
  {
    "name": "CUSTOM HOUSE, NEAR BALAJI TEMPLE, KANDLA - 370210",
    "code": "INIXY1"
  },
  {
    "name": "Varavda",
    "code": "INVRD1"
  },
  {
    "name": "Uttan",
    "code": "INUTN1"
  },
  {
    "name": "Ulwa",
    "code": "INULW1"
  },
  {
    "name": "Trombay",
    "code": "INTMP1"
  },
  {
    "name": "Thana",
    "code": "INTNA1"
  },
  {
    "name": "Miraj",
    "code": "INMRJ6"
  },
  {
    "name": "Manori",
    "code": "INMNR1"
  },
  {
    "name": "Mandwa",
    "code": "INMNW1"
  },
  {
    "name": "ICD CONCOR, DHANDARI KALAN, LUDHIANA PIN-141001",
    "code": "INLDH6"
  },
  {
    "name": "Malwan",
    "code": "INMLW1"
  },
  {
    "name": "Kumbharu",
    "code": "INKMB1"
  },
  {
    "name": "Bassein",
    "code": "INBSN1"
  },
  {
    "name": "BANKOT PORT, UMROLI VILL, MANDANGAD TK,MAHARASHTRA",
    "code": "INBKT1"
  },
  {
    "name": "Bandra",
    "code": "INBND1"
  },
  {
    "name": "Arnala",
    "code": "INANL1"
  },
  {
    "name": "Kiranpani",
    "code": "INKRP1"
  },
  {
    "name": "Kelwa",
    "code": "INKIW1"
  },
  {
    "name": "KELSHI PORT, UMBERSHET VIL, DAPOLI TK, MAHARASHTRA",
    "code": "INKSH1"
  },
  {
    "name": "Karanja",
    "code": "INKRN1"
  },
  {
    "name": "Kalyan",
    "code": "INKLY1"
  },
  {
    "name": "Jaitapur",
    "code": "INJTP1"
  },
  {
    "name": "JAIGAD PORT, RATNAGIRI DISTRICT, MAHARASHTRA",
    "code": "INJGD1"
  },
  {
    "name": "CFS NASIK, COMPLEX OF CWC AMBAD NASIK MAHARASHTRA",
    "code": "INNSK6"
  },
  {
    "name": "ICD NAGPUR NR NARENDRA NAGAR NAGPUR 440027",
    "code": "INNGP6"
  },
  {
    "name": "ICD DIGHI TALERA NAGAR PUNE ALANDI ROAD DIGHI PUNE",
    "code": "INDIG6"
  },
  {
    "name": "NAGPUR AIR CARGO, MAHARASHTRA",
    "code": "INNAG4"
  },
  {
    "name": "NEW CUSTOM HOUSE, PANAMBUR, MANGALORE 575010",
    "code": "INNML1"
  },
  {
    "name": "AIR CARGO COMPLEX, LOHEGAM, PUNE, MAHARASHTRA",
    "code": "INPNQ4"
  },
  {
    "name": "ICD MALIWADA, DAULATABAD, AURANGABAD",
    "code": "INMWA6"
  },
  {
    "name": "Panvel",
    "code": "INPVL6"
  },
  {
    "name": "ACC KOLKATA, 15/1 STRANDROAD, CUSTOM HOUSE KOLKATA",
    "code": "INCCU4"
  },
  {
    "name": "15/1 STRAND ROAD, CUSTOM HOUSE, KOLKATA - 700001",
    "code": "INCCU1"
  },
  {
    "name": "Shriwardhan",
    "code": "INSWD1"
  },
  {
    "name": "Satpati",
    "code": "INSTP1"
  },
  {
    "name": "Rajpuri",
    "code": "INRJR1"
  },
  {
    "name": "Purangad",
    "code": "INPRG1"
  },
  {
    "name": "Palshet",
    "code": "INPSH1"
  },
  {
    "name": "Nivti",
    "code": "INNVT1"
  },
  {
    "name": "Newapur",
    "code": "INNWP1"
  },
  {
    "name": "Nandgaon",
    "code": "INNDG1"
  },
  {
    "name": "Murad",
    "code": "INMRD1"
  },
  {
    "name": "Mumbai DP-II",
    "code": "INGRD6"
  },
  {
    "name": "Mumbai -DP-I",
    "code": "INGRR6"
  },
  {
    "name": "Mora",
    "code": "INMRA1"
  },
  {
    "name": "ICD MULUND, MUMBAI, MAHARASHTRA",
    "code": "INMUL6"
  },
  {
    "name": "Balet",
    "code": "INBLTB"
  },
  {
    "name": "LCS ZOKHAWTHAR, CHAMPHAI, MIZORAM - 796321.",
    "code": "INCHPB"
  },
  {
    "name": "Demagir",
    "code": "INDMRB"
  },
  {
    "name": "Bahabal Pur",
    "code": "INBBP1"
  },
  {
    "name": "MUNDRA SEZ PORT, MUNDRA, GUJARAT",
    "code": "INMUN1"
  },
  {
    "name": "PARADEEP PORT CUSTOM HOUSE PARADEEP ORISSA 754142",
    "code": "INPRT1"
  },
  {
    "name": "BHUBANESWAR AIR CARGO, BHUBANESWAR, ORISSA",
    "code": "INBBI4"
  },
  {
    "name": "GOPALPUR PORT, ORISSA",
    "code": "INGPR1"
  },
  {
    "name": "Alibag",
    "code": "INABG1"
  },
  {
    "name": "REDI PORT, RATNAGIRI, MAHARASHTRA",
    "code": "INRED1"
  },
  {
    "name": "Khopta (EPZ/SEZ)",
    "code": "INKHP6"
  },
  {
    "name": "SEEPZ SPECIAL EONOMIC ZONE ANDHERI EAST MUMBAI 093",
    "code": "INBOM6"
  },
  {
    "name": "ICD CHINCHWAD CONCOR RLY GOODS SHED CHINCHWAD PUNE",
    "code": "INCCH6"
  },
  {
    "name": "ICD WALUJ, AURANGABAD - 431030",
    "code": "INWAL6"
  },
  {
    "name": "F-II BLOCK, YESHWANT NAGAR, PIMPRI, PUNE 400018",
    "code": "INPMP6"
  },
  {
    "name": "LCS ROAD CARGO, ATTARI ROAD, AMRITSAR, PUNJAB",
    "code": "INATRB"
  },
  {
    "name": "ICD-PSWC, AMBALA-KALKA HIGHWAY, DAPPAR, DERABASSI",
    "code": "INDPR6"
  },
  {
    "name": "SGRD JEE INTERNATIONAL AIRPORT, AMRITSAR",
    "code": "INATQ4"
  },
  {
    "name": "ICD JALANDHAR, DHOGRI ROAD NOORPUR JALANDHAR",
    "code": "INJUC6"
  },
  {
    "name": "Bhatinda",
    "code": "INBTI6"
  },
  {
    "name": "Munabao Railway Station",
    "code": "INMNB2"
  },
  {
    "name": "JNCH, NHAVA SHEVA, TAL:URAN, DIST-RAIGAD-400707",
    "code": "INNSA1"
  },
  {
    "name": "DAHANU PORT, MAHARASHTRA",
    "code": "INDHU1"
  },
  {
    "name": "REVDANDA PORT,VILL.BAVALE-DIST. RAIGAD,MAHARASHTRA",
    "code": "INRVD1"
  },
  {
    "name": "Ratnagiri",
    "code": "INRTC1"
  },
  {
    "name": "RANPAR PORT, RATNAGIRI DIST, MAHARASHTRA-415616",
    "code": "INRNR1"
  },
  {
    "name": "DHARAMTAR PORT, ALIBAG, MAHARASHTRA",
    "code": "INDMT1"
  },
  {
    "name": "LCS MOREH, TENGNOUPAL DISTRICT, MANIPUR",
    "code": "INMREB"
  },
  {
    "name": "Imphal",
    "code": "INIMF4"
  },
  {
    "name": "LCS BAGHMARA, SOUTH GARO HILLS, MEGHALAYA- 794102",
    "code": "INBGMB"
  },
  {
    "name": "LCS BORSORA, SOUTH WEST KHASI HILLS, MEGHALAYA- 06",
    "code": "INBRAB"
  },
  {
    "name": "LAND CUSTOMS STATION SHELAGENCYAZAR, MEGHALAYA",
    "code": "INSBZB"
  },
  {
    "name": "Ryngku",
    "code": "INRGUB"
  },
  {
    "name": "LCS MAHENDRAGANJ, MEGHALAYA",
    "code": "INMGHB"
  },
  {
    "name": "LCS GHASUAPARA, SOUTH GARO HILLS, MEGHALAYA-02",
    "code": "INGHPB"
  },
  {
    "name": "LAND CUSTOMS STATION, DAWKI, MEGHALAYA",
    "code": "INDWKB"
  },
  {
    "name": "LCS DALU, KILLAPARA, MEGHALAYA-794103",
    "code": "INDLUB"
  },
  {
    "name": "LAND CUSTOMS STATION BHOLAGANJ, MEGHALAYA",
    "code": "INBOLB"
  },
  {
    "name": "ICD PATPARGANJ, GAZIPUR, NR GAZIPUR BUS DEPOT, ND",
    "code": "INPPG6"
  },
  {
    "name": "ICD KARUR, ANDANDKOIL WEST, KUTKADAI, KARUR, TN",
    "code": "INKAR6"
  },
  {
    "name": "ICD IRUGUR OPP IOC TERMINAL IRUGUR COIMBATORE",
    "code": "INIGU6"
  },
  {
    "name": "MEPZ SPECIAL ECONOMIC ZONE, CHENNAI",
    "code": "INMAA6"
  },
  {
    "name": "Kulasekarapatnam",
    "code": "INKSP1"
  },
  {
    "name": "Portonovo",
    "code": "INPTN1"
  },
  {
    "name": "Thopputhurai",
    "code": "INTPH1"
  },
  {
    "name": "ICD THUDIALUR 2/235C M'PALAYAM ROAD COIMBATORE",
    "code": "INTDE6"
  },
  {
    "name": "ICD 113 CONCOR COMPLEX SECTOR III PITHAMPUR DHAR",
    "code": "ININD6"
  },
  {
    "name": "MKP PVT LTD, TR PATTINAM POST, KARAIKAL 609606",
    "code": "INKRK1"
  },
  {
    "name": "CUSTOM HOUSE NO.1 DUMAS STREET PONDICHEERY",
    "code": "INPNY1"
  },
  {
    "name": "ICD PULICHAPALLAM, PONDY MAIN ROAD, PONDICHERRY",
    "code": "INPNY6"
  },
  {
    "name": "OTHERS",
    "code": "OTHERS"
  },
  {
    "name": "AMRITSAR RAIL CARGO, AMRITSAR, PUNJAB",
    "code": "INASR2"
  },
  {
    "name": "Attari Railway Station",
    "code": "INATT2"
  },
  {
    "name": "ICD IRUNGATTUKOTTAL, SRIPERUMBUDUR - 602105",
    "code": "INILP6"
  },
  {
    "name": "CUDDALORE PORT, CUSTOM HOUSE CUDDALORE, TN- 607003",
    "code": "INCDL1"
  },
  {
    "name": "C H, NO 4 FIRSTLINE BEACH NAGAPATTINAM 611001",
    "code": "INNPT1"
  },
  {
    "name": "Tirukkadayyur",
    "code": "INTYR1"
  },
  {
    "name": "Valinokkam",
    "code": "INVKM1"
  },
  {
    "name": "ICD SINGNALLUR NEELIKONNAMPALAYAM COIMBATORE",
    "code": "INSLL6"
  },
  {
    "name": "ICD TIRUPUR RAAKIYAPALAYAM AVINASHI TIRUPUR 54",
    "code": "INTUP6"
  },
  {
    "name": "Salem",
    "code": "INSXT6"
  },
  {
    "name": "ICD CONCOR KANAKPURA JAIPUR",
    "code": "INKKU6"
  },
  {
    "name": "Jodhpur- Boranda (EPZ/SEZ)",
    "code": "INBRN6"
  },
  {
    "name": "FPO JAIPUR",
    "code": "INJAI5"
  },
  {
    "name": "RIICO SEZ - II, SITAPURA, JAIPUR - 302022",
    "code": "INJSZ6"
  },
  {
    "name": "ICD CONCOR NEW POWER HOUSE BHAGAT KI KOTHI JODHPUR",
    "code": "INBGK6"
  },
  {
    "name": "Barmer Railway Station",
    "code": "INBMR2"
  },
  {
    "name": "AIR CARGO COMPLEX SANGANER JAIPUR",
    "code": "INJAI4"
  },
  {
    "name": "ICD BHILWARA SECTOR 5 AZAD NAGAR BHILWARA 342005",
    "code": "INBHL6"
  },
  {
    "name": "ICD RAJSICO BASNI PHASE-II JODHPUR 342005",
    "code": "INJUX6"
  },
  {
    "name": "Udaipur",
    "code": "INUDZ6"
  },
  {
    "name": "ICD CONCOR RAWATHA ROAD POST: MANDANA KOTA",
    "code": "INKTT6"
  },
  {
    "name": "ICD RAJSICO SECTOR 9 UIT COLONY BHIWADI RAJASTHAN",
    "code": "INBWD6"
  },
  {
    "name": "LCS CHAMURCHI, SILIGURI, WEST BENGAL",
    "code": "INCHMB"
  },
  {
    "name": "ICD ARAKKONAM, MARUTI PARK NETAJI NAGAR KAINOOR-3",
    "code": "INAJJ6"
  },
  {
    "name": "Madurai ICD",
    "code": "INIXM6"
  },
  {
    "name": "ICD CHETTIPALAYAM, SF129 AVINASHI TALUK TIRUPUR 52",
    "code": "INCHE6"
  },
  {
    "name": "LCS BANBASA, CHAMPAWAT, UTTARAKHAND",
    "code": "INBSAB"
  },
  {
    "name": "LCS GAURIPHANTA, PALIA, DIST.LAKHIMPUR KHERI, U.P.",
    "code": "INGAIB"
  },
  {
    "name": "Gunji",
    "code": "INGJIB"
  },
  {
    "name": "LCS JHULAGHAT, DIST. PITHAURAGARH, UTTARAKHAND.",
    "code": "INJHOB"
  },
  {
    "name": "LAND CUSTOMS STATION, KATARNIAGHAT",
    "code": "INKTGB"
  },
  {
    "name": "LAND CUSTOMS STATION, NEPALGUNJ ROAD",
    "code": "INNGRB"
  },
  {
    "name": "MADHOSINGH ICD, UTTAR PRADESH",
    "code": "INMBS6"
  },
  {
    "name": "Tondi",
    "code": "INTND1"
  },
  {
    "name": "ICD VEERAPANDI, SF 352 & 353 PALLADAM ROAD TIRUPUR",
    "code": "INTHO6"
  },
  {
    "name": "Rameshwaram",
    "code": "INRWR1"
  },
  {
    "name": "Pamban",
    "code": "INPMB1"
  },
  {
    "name": "Kilakari",
    "code": "INKKR1"
  },
  {
    "name": "Colachel",
    "code": "INCHL1"
  },
  {
    "name": "Tiruvallur ICD",
    "code": "INTRL6"
  },
  {
    "name": "APL Dadri",
    "code": "INAPL6"
  },
  {
    "name": "TIKONIA LCS, LUCKNOW CUSTOMS, UTTAR PRADESH",
    "code": "INTKNB"
  },
  {
    "name": "LCS SONAULI, MAHARAJGANJ DIST, UP",
    "code": "INSNLB"
  },
  {
    "name": "LCS, KHUNWA, DIST. SIDDHARTHANAGAR, U.P.",
    "code": "INKWAB"
  },
  {
    "name": "ICD JRY KANPUR, PO: RK NAGAR KANPUR - 208012",
    "code": "INKNU6"
  },
  {
    "name": "Jarwa",
    "code": "INJWAB"
  },
  {
    "name": "ICD, SURAJPUR- GREATER NOIDA",
    "code": "INSJR6"
  },
  {
    "name": "LCS DHARCHULA, DIST. PITHAURAGARH, UTTARAKHAND",
    "code": "INDAGENCY"
  },
  {
    "name": "BERHNI LCS, LUCKNOW CUSTOMS, UTTAR PRADESH",
    "code": "INBNYB"
  },
  {
    "name": "Coimbatore",
    "code": "INCBE6"
  },
  {
    "name": "TIRUCHIRAPALLI AIR CARGO, TAMIL NADU",
    "code": "INTRZ4"
  },
  {
    "name": "ACC COIMBATORE CIVIL AERODROME COIMBATORE - 04",
    "code": "INCJB4"
  },
  {
    "name": "Veppalodai",
    "code": "INVEP1"
  },
  {
    "name": "Rameshwaram",
    "code": "INRAM1"
  },
  {
    "name": "Mandapam",
    "code": "INMDP1"
  },
  {
    "name": "KAMARAJAR PORT LIMITED, 60, RAJAJI SALAI- CHENNAI.",
    "code": "INENR1"
  },
  {
    "name": "LAND CUSTOMS STATION- AGARTALA, TRIPURA",
    "code": "INAGTB"
  },
  {
    "name": "LAND CUSTOMS STATION- MUHURIGHAT",
    "code": "INMHGB"
  },
  {
    "name": "Sabroom",
    "code": "INSABB"
  },
  {
    "name": "LAND CUSTOMS STATION- SRIMANTAPUR, TRIPURA",
    "code": "INSMPB"
  },
  {
    "name": "LAND CUSTOMS STATION, OLD RANGHNA BAZAR, TRIPURA",
    "code": "INRGBB"
  },
  {
    "name": "LCS KHOWAIGHAT, PURAN BAZAR KHOWAI, TRIPURA 799201",
    "code": "INKWGB"
  },
  {
    "name": "Dhalaighat",
    "code": "INDHLB"
  },
  {
    "name": "Kel Sahar Subdivision",
    "code": "INKELB"
  },
  {
    "name": "ICD SABARMATI KALIGAM SABARMATI AHMEDABAD 382470",
    "code": "INSBI6"
  },
  {
    "name": "LCS JAIGAON, ALIPURDUAR DIST, WEST BENGAL",
    "code": "INJIGB"
  },
  {
    "name": "SINGHABAD RAILWAY STATION, MALDA, WEST BENGAL",
    "code": "INSNG2"
  },
  {
    "name": "RANAGHAT RAILWAY STATION, NADIA, WEST BENGAL",
    "code": "INRNG2"
  },
  {
    "name": "LCS RADHIKAPUR RAILWAY STATION, WEST BENGAL",
    "code": "INRDP2"
  },
  {
    "name": "LCS PETRAPOLE, BONGAON, WEST BENGAL",
    "code": "INPTPB"
  },
  {
    "name": "LCS PANITANKI (NAXALBARI), WEST BENGAL",
    "code": "INPNTB"
  },
  {
    "name": "ACC SHANGHUMUGHAM THIRUVANANTHAPURAM KERALA",
    "code": "INTRV4"
  },
  {
    "name": "ICD LONI, DISTRICT GHAZIABAD, UP",
    "code": "INLON6"
  },
  {
    "name": "CPL Dadri",
    "code": "INCPL6"
  },
  {
    "name": "ICD TUGHLAKABAD, NEW DELHI 110020",
    "code": "INTKD6"
  },
  {
    "name": "ICD Badohi",
    "code": "INBDH6"
  },
  {
    "name": "TTP Dadri",
    "code": "INTTP6"
  },
  {
    "name": "ICD TUTICORIN, 1663/2B HARBOUR EXP. ROAD TUTICORIN",
    "code": "INTUT6"
  },
  {
    "name": "CUSTOM HOUSE, HARBOUR ESTATE, TUTICORIN 628004",
    "code": "INTUT1"
  },
  {
    "name": "Sukhia Pokhari",
    "code": "INSKPB"
  },
  {
    "name": "Sitai",
    "code": "INSTIB"
  },
  {
    "name": "Hingalganj",
    "code": "INHGLB"
  },
  {
    "name": "LCS - GHOJADANGA, PANITOR, WEST BENGAL",
    "code": "INGJXB"
  },
  {
    "name": "LCS GEDE RAILWAY STATION, WEST BENGAL",
    "code": "INGED2"
  },
  {
    "name": "Patrapole",
    "code": "INPTP8"
  },
  {
    "name": "LCS CHANGRABANDHA, SILIGURI, WEST BENGAL",
    "code": "INCBDB"
  },
  {
    "name": "LCS FULBARI, SILIGURI, WEST BENGAL",
    "code": "INFBRB"
  },
  {
    "name": "MANIKANCHAN SEZ, SALTLAKE, KOLKATA 700091",
    "code": "INSLT6"
  },
  {
    "name": "Star Track Terminal Pvt Ltd ICD Dadri",
    "code": "INSTT6"
  },
  {
    "name": "Agra",
    "code": "INAGR4"
  },
  {
    "name": "ICD Dadri, Gautam Budh Nagar, UP -203207",
    "code": "INDER6"
  },
  {
    "name": "MORADABAD SEZ PAKWARA DINGARPUR RD MORADABAD244102",
    "code": "INMBC6"
  },
  {
    "name": "NOIDA SPECIAL ECONOMIC ZONE, NOIDA, G. B. NAGAR",
    "code": "INNDA6"
  },
  {
    "name": "ICD SAHARANPUR, UP",
    "code": "INSRE6"
  },
  {
    "name": "Meerut",
    "code": "INMTC6"
  },
  {
    "name": "ICD LOCOSHED MORADABAD UP",
    "code": "INMBD6"
  },
  {
    "name": "ICD CHAKERI, GT ROAD, KANPUR -208007",
    "code": "INCPC6"
  },
  {
    "name": "Varanasi",
    "code": "INBSB6"
  },
  {
    "name": "ICD AGRA, EAST BANK, MOTIMAHAL, AGRA UP",
    "code": "INBLJ6"
  },
  {
    "name": "AIR CARGO COMPLEX, BABATPUR, VARANASI, UP",
    "code": "INVNS4"
  },
  {
    "name": "Bareilly",
    "code": "INBEK4"
  },
  {
    "name": "LUCKNOW AIR CARGO, LUCKNOW, UTTAR PRADESH",
    "code": "INLKO4"
  },
  {
    "name": "Kanpur",
    "code": "INKNU4"
  },
  {
    "name": "LCS- HILLI, BASUDEVPUR, WEST BENGAL",
    "code": "INHLIB"
  },
  {
    "name": "VIJAYDURG PORT, PUNE CUSTOMS, MAHARASHTRA",
    "code": "INVYD1"
  },
  {
    "name": "Tadri",
    "code": "INTRI1"
  },
  {
    "name": "Belekeri",
    "code": "INBLK1"
  },
  {
    "name": "Maroli",
    "code": "INMLI1"
  },
  {
    "name": "SEA-PORT , ALLEPEY",
    "code": "INALF1"
  },
  {
    "name": "Namkhana",
    "code": "INNKNB"
  },
  {
    "name": "Lalgola Town",
    "code": "INLGLB"
  },
  {
    "name": "LAND CUSTOMS STATION-MAHADIPUR, MALDA, WEST BENGAL",
    "code": "INMHDB"
  },
  {
    "name": "Jalpaiguri",
    "code": "INJPGB"
  },
  {
    "name": "ALLIED ICD SERVICES LTD, EPIP, BANSKOPA, DURGAPUR",
    "code": "INDUR6"
  },
  {
    "name": "Tungi",
    "code": "INTNGB"
  },
  {
    "name": "LCS- T.T.SHED (KIDDERPORE), WEST BENGAL",
    "code": "INTTSB"
  },
  {
    "name": "RELIANCE SEZ, VILL-MOTIKHAVDI, JAMNAGAR",
    "code": "INLPJ6"
  },
  {
    "name": "DABHOL PORT,ANJANVEL PO,RATNAGIRI DIST,MAHARASHTRA",
    "code": "INDHP1"
  },
  {
    "name": "Dhanu - Shkodi",
    "code": "INDSK1"
  },
  {
    "name": "Getandah",
    "code": "INGTZB"
  },
  {
    "name": "Jalgaon",
    "code": "INJAL6"
  },
  {
    "name": "ICD CHEHERTTA AMRITSAR PUNJAB",
    "code": "INASR6"
  },
  {
    "name": "ICD THAR DRY PORT BARMER ROAD PAL GAON JODHPUR",
    "code": "INTHA6"
  },
  {
    "name": "ICD, KHEDA, 13B,SECTOR 3, PITHAMPUR,MADHYA PRADESH",
    "code": "INKHD6"
  },
  {
    "name": "ICD THAR DRY PORT KADI ROAD SANAND AHMEDABAD",
    "code": "INSAU6"
  },
  {
    "name": "Vedanta Aluminium Ltd.",
    "code": "INJHA2"
  },
  {
    "name": "Dronagiri Multi Service SEZ",
    "code": "INBAP6"
  },
  {
    "name": "FALTA SPECIAL ECONOMIC ZONE, KOLKATA",
    "code": "INFLT6"
  },
  {
    "name": "Bagdogra",
    "code": "INIXB4"
  },
  {
    "name": "Raddipalem",
    "code": "INRPL6"
  },
  {
    "name": "INDORE SEZ, PITHAMPURA, DHAR, MP-454775",
    "code": "INIDR6"
  },
  {
    "name": "Delhi Railway Station",
    "code": "INDLI2"
  },
  {
    "name": "Bheemunipatnam",
    "code": "INBNP1"
  },
  {
    "name": "Talpona",
    "code": "INTPN1"
  },
  {
    "name": "CUSTOM HOUSE, GPPL PIPAVAV RAJULA, AMRELI GUJARAT",
    "code": "INPAV1"
  },
  {
    "name": "ALANG PORT, PARIMAL CHOWK, BHAVNAGAR, GUJARAT",
    "code": "INALA1"
  },
  {
    "name": "Village Namgaya Shipkila",
    "code": "INNGSB"
  },
  {
    "name": "Anijengo",
    "code": "INANG1"
  },
  {
    "name": "FPO, 5TH MAIN, 4TH CROSS, BEHIND UMA CHAMARAJPET",
    "code": "INBLR5"
  },
  {
    "name": "Kakinada",
    "code": "INCOI6"
  },
  {
    "name": "Surasani - Yanam",
    "code": "INSRV1"
  },
  {
    "name": "Jafrabad",
    "code": "INJBD1"
  },
  {
    "name": "CUSTOM HOUSE, PORT AREA VISAKHAPATNAM 530035",
    "code": "INVTZ1"
  },
  {
    "name": "PIONEER ALUMINUM SEZ GKODURU, VISHKHAPATNAM 531113",
    "code": "INNRP6"
  },
  {
    "name": "VBTL SEZ MEDAK",
    "code": "INMOV6"
  },
  {
    "name": "RLL SEZ/Medak",
    "code": "INKOH6"
  },
  {
    "name": "WFPML SEZ KOVVUR",
    "code": "INKVR6"
  },
  {
    "name": "SEZ/Kakinada",
    "code": "INCOA6"
  },
  {
    "name": "APIIC Ltd SEZ Medak",
    "code": "INMDE6"
  },
  {
    "name": "TSIIC PHARAM SEZ, MAHABOOB NAGAR- 509302",
    "code": "INGLY6"
  },
  {
    "name": "PARRY SUGAR REFINERY SEZ VAKALAPUDI KAKINADA533003",
    "code": "INCOP6"
  },
  {
    "name": "APACHE FOOTWEAR SEZ, MAMBATTU, NELLORE, AP- 524401",
    "code": "INSPE6"
  },
  {
    "name": "HYDERABAD GEMS SEZ LIMITED",
    "code": "INFMH6"
  },
  {
    "name": "TSIIC SEZ AEROSPACE ADIBATLA RANGA REDDY TELANGANA",
    "code": "INFMA6"
  },
  {
    "name": "NG REALTY SEZ/Taluka",
    "code": "INVLN6"
  },
  {
    "name": "FAB CITY SPV SEZ, MAHESHWARAM, RANGAREDDY 501506",
    "code": "INURF6"
  },
  {
    "name": "TSIIC, LALGADI MARKET, SHAMEERPET, TELANGANA",
    "code": "INMEA6"
  },
  {
    "name": "SANOFI HEALTHCARE SEZ MUPPIREDDYPALLY, MEDAK",
    "code": "INDBS6"
  },
  {
    "name": "GMR HYDERABAD AVIATION SEZ, SHAMSHABAD 500409",
    "code": "INURG6"
  },
  {
    "name": "SRI CITY SEZ, SATHYAVEDU, TIRUPATI, AP -517646",
    "code": "INTAS6"
  },
  {
    "name": "CONCOR ICD,NR LOCO SHED,JAORA RD.,RATLAM(MP)457001",
    "code": "INRTM6"
  },
  {
    "name": "ASPEN INFRA PADUBIDRI SEZ, HEJAMADI, UDUPI 574111",
    "code": "INUDI6"
  },
  {
    "name": "M/S CONCOR, ENNORE HIGH ROAD,TIRUVOTTIYUR, CHENNAI",
    "code": "INTVT6"
  },
  {
    "name": "STARGAZE PROPERTIESSEZ MAHESHWARAM HYDERABAD501510",
    "code": "INFMS6"
  },
  {
    "name": "J T HOLDINGS SEZ MAHESWARAM R RDISTRICT TEL- 500005",
    "code": "INFMJ6"
  },
  {
    "name": "SUNDEW PROPERTIES SEZ 64P MADHAPUR R R DIST 500081",
    "code": "INLPI6"
  },
  {
    "name": "Kalamboli Multi Service SEZ",
    "code": "INLKM6"
  },
  {
    "name": "Ulwe IT/ITES-A-SEZ",
    "code": "INBAU6"
  },
  {
    "name": "Ulwe IT/ITES-B-SEZ",
    "code": "INBAI6"
  },
  {
    "name": "Ulwe GEM & Jewellery SEZ",
    "code": "INBAG6"
  },
  {
    "name": "Ulwe Multi Services SEZ",
    "code": "INBAM6"
  },
  {
    "name": "ASPENPARK INFRA COIMBATORE PVT LTD., SEZ, 641659",
    "code": "INCBS6"
  },
  {
    "name": "ICD, MARRIPALAM, DISTRICT - GUNTUR, A.P.",
    "code": "INGNR6"
  },
  {
    "name": "GANGAVARAM PORT, ANDHRA PRADESH",
    "code": "INGGV1"
  },
  {
    "name": "STERLING INFRASTRUCTURE SEZ JAMBUSAR BHARUCH392180",
    "code": "INBHS6"
  },
  {
    "name": "ADANI PORTS AND SEZ, MUNDRA, KUTCH, GUJARAT",
    "code": "INAJM6"
  },
  {
    "name": "SIPCOT SEZ, GANGAIKONDAN",
    "code": "INTEN6"
  },
  {
    "name": "APIIC, MULTI PRODUCT SEZ, ATCHUTHAPURAM -531001",
    "code": "INAKP6"
  },
  {
    "name": "HETERO INFRA SEZ NAKKAPALLY, VISHAKHAPATNAM 531113",
    "code": "INTNI6"
  },
  {
    "name": "VISAKHA PHARMACITY LTD SEZ, ANAKAPALLI-531019",
    "code": "INAKR6"
  },
  {
    "name": "DIVIS AGENCYORATORIES LTD SEZ CHIPADA V'PATANAM531162",
    "code": "INVZM6"
  },
  {
    "name": "BRANDIX INDIA APPAREL CITY SEZ ATCHUTHAPURAM531011",
    "code": "INAKB6"
  },
  {
    "name": "ICD GRFL, VILLAGE PIYALA FARIDABAD",
    "code": "INBFR6"
  },
  {
    "name": "ICD MATHILAKAM, THRISSUR DIST, KERALA",
    "code": "INTCR6"
  },
  {
    "name": "SEZ ARSHIYA LTD., PANVEL, RAIGAD",
    "code": "INPNV6"
  },
  {
    "name": "MultiService-SEZ/Kalamboli",
    "code": "INKLM6"
  },
  {
    "name": "IT/ITES-C SEZ/Ulwe",
    "code": "INBAT6"
  },
  {
    "name": "SERUM BIO-PHARMA PARK SEZ, HADAPSAR MANJRI, PUNE",
    "code": "INPNQ6"
  },
  {
    "name": "MAHINDRA WORLD CITY SEZ, CHENGALPATTU, TAMIL NADU",
    "code": "INCGI6"
  },
  {
    "name": "MAHINDRA WORLD CITY SEZ (APPARELS) CHENNAI",
    "code": "INCGA6"
  },
  {
    "name": "MAHINDRA WORLD CITY SEZ(AUTO ANCILLARY), CHENNAI",
    "code": "INCGL6"
  },
  {
    "name": "NOKIA TELECOM SEZ, SRIPERUMBUDUR KACHIPURAM602105",
    "code": "INCJN6"
  },
  {
    "name": "SIPCOT LTD SEZ, ELEC-HARD-HITECH, SRIPERUMBUDUR",
    "code": "INCJS6"
  },
  {
    "name": "SIPCOT LTD, GROWTH CENTER SEZ, ORAGADAM",
    "code": "INCJO6"
  },
  {
    "name": "FLEXTRONICS TECH INDIA SEZ, SRIPERUMBUDUR, 602106",
    "code": "INCJF6"
  },
  {
    "name": "CHEYYAR SEZ, THIRUVANNAMALAI, VELLORE",
    "code": "INVTC6"
  },
  {
    "name": "CCCL FOOD PORT SEZ LTD SEKKARAKUDI TUTICORIN628104",
    "code": "INTNC6"
  },
  {
    "name": "AMRL INTERNATIONAL HITECH CITY LTD, SEZ, NANGUNERI",
    "code": "INNNN6"
  },
  {
    "name": "PLATINUM HOLDINGS SEZ, NAVALUR, CHENNAI 600130",
    "code": "INTBM6"
  },
  {
    "name": "IG3 INFRA LTD, SEZ, UTHUKULLI, THIRUPPUR - 638751",
    "code": "INUKL6"
  },
  {
    "name": "MULTI SECTOR SEZ, SIPCOT, PERUNDURAI 638052",
    "code": "INPYS6"
  },
  {
    "name": "FRONTIER LIFELINE PVT. LTD",
    "code": "INGDP6"
  },
  {
    "name": "Kota-Ravtha Road",
    "code": "INRDT6"
  },
  {
    "name": "KLPL ICD, PANKI, KANPUR",
    "code": "INPNK6"
  },
  {
    "name": "SEZ ARSHIYA NORTHERN FTWZ LTD, BULANDSHAR, UP",
    "code": "INBUL6"
  },
  {
    "name": "DLF INFO CITY SEZ GACHIBOWLI HYDERABAD 500032",
    "code": "INLPD6"
  },
  {
    "name": "IFFCO KISAN SEZ RACHARLAPADU, NELLORE, AP- 524319",
    "code": "INTMI6"
  },
  {
    "name": "Rassi-SEZ/Anantpur",
    "code": "INHUR6"
  },
  {
    "name": "DR REDDY'S AGENCYORATORIES LTD SEZ SRIKAKULAM 532409",
    "code": "INVZR6"
  },
  {
    "name": "APIIC-SEZ/Cuddapah",
    "code": "INCDP6"
  },
  {
    "name": "GIDC ELECTRONIC PARK SEZ, GHANDINAGAR- 382028",
    "code": "INGNG6"
  },
  {
    "name": "GANESH HOUSING CORPN SEZ CHARODI DASCROI AHMEDABAD",
    "code": "INADG6"
  },
  {
    "name": "3RD EYE VOICE SEZ, CCIPL, DASCROI AHMEDABAD 380060",
    "code": "INADC6"
  },
  {
    "name": "SREHPL-SEZ/GANDHINAGAR",
    "code": "INGNS6"
  },
  {
    "name": "MRPL-SEZ/AHMEDABAD",
    "code": "INADM6"
  },
  {
    "name": "CGRPL-SEZ/AHMEDABAD",
    "code": "INADR6"
  },
  {
    "name": "TATA CONSULTANCY SERVICES SEZ GANDHINANGAR 382007",
    "code": "INGNT6"
  },
  {
    "name": "Dishman-Pharmaceutical-SEZ/Kalyangadh",
    "code": "INVLD6"
  },
  {
    "name": "KRIBHCO INFSTR LTD,HAZIRA,KRIBHCO NGR,SURAT,GUJRAT",
    "code": "INHZR6"
  },
  {
    "name": "LARSEN & TOUBRO LTD SEZ, ANKHOL, VADODAARA - 390019",
    "code": "INBRL6"
  },
  {
    "name": "ICD CONCOR, SECTOR 25 FARIDABAD",
    "code": "INBVC6"
  },
  {
    "name": "KIADB MANGALORE",
    "code": "INMQK6"
  },
  {
    "name": "KARLE PROJECTS, SEZ, NAGAVARA, BENGALURU",
    "code": "INYNK6"
  },
  {
    "name": "EMBASSY TECH SEZ, VARTHUR HOBLI, BANGALORE - 560037",
    "code": "INBLV6"
  },
  {
    "name": "Renaissance SEZ/Mysore",
    "code": "INMSR6"
  },
  {
    "name": "DIVYASREE TECHNOPARK SEZ, HOBLI, BENGALURU- 560037",
    "code": "INKJD6"
  },
  {
    "name": "HCL TECHNOLOGIES LTD, JIGANI, ATTIBELE, BENGALURU",
    "code": "INKJH6"
  },
  {
    "name": "MILESTONE BUILDCON SEZ, CHOKKANAHALI, BENGULURU",
    "code": "INYNM6"
  },
  {
    "name": "Brigade Enter SEZ/Kannada",
    "code": "INMAB6"
  },
  {
    "name": "Opta Infra SEZ/Hassan",
    "code": "INHAO6"
  },
  {
    "name": "Opta Infra SEZ/Mysore",
    "code": "INMYO6"
  },
  {
    "name": "KIADB AEROSPACE SEZ, BENGALURU - 562110",
    "code": "INSBK6"
  },
  {
    "name": "Infosys SEZ/Bangalore",
    "code": "INSBL6"
  },
  {
    "name": "ULCCS SEZ, NELLIKODE, KOZHIKODE, KERALA - 733102",
    "code": "INCLU6"
  },
  {
    "name": "KSITIL SEZ/Payyanoor",
    "code": "INPAK6"
  },
  {
    "name": "KSITIL, SEZ, MULAVANA, KOLLAM, KERALA - 695581",
    "code": "INKUK6"
  },
  {
    "name": "ELECTRONICS TECH. PARK I SEZ TRIVANDRUM 695581",
    "code": "INKZE6"
  },
  {
    "name": "ELECTRONICS TECH PARK II SEZ TRIVANDRUM 695581",
    "code": "INKZT6"
  },
  {
    "name": "ELECTRONIC TECHNOLOGY PARK-III, TRIVANDRUM 695581",
    "code": "INKZP6"
  },
  {
    "name": "KSITIL SEZ/Alappuzha",
    "code": "INAMK6"
  },
  {
    "name": "KINFRA ELECTRONIC SEZ KALAMASSERY, ERNAKULAM695010",
    "code": "INKLK6"
  },
  {
    "name": "SMART CITY (KOCHI) INFRA SEZ, ERNAKULAM- 682037",
    "code": "INKLS6"
  },
  {
    "name": "INFOPARK PHASE -II, KUNNATHUNAD, ERNAKULAM 682042",
    "code": "INKMI6"
  },
  {
    "name": "Bluestar Realtors SEZ/Ernakulam",
    "code": "INKLB6"
  },
  {
    "name": "Dadri Greater Noida",
    "code": "INALP6"
  },
  {
    "name": "ASPEN PARK INFRA LTD SEZ WAGHODIA, VADODARA 391760",
    "code": "INBRS6"
  },
  {
    "name": "GLOBAL VILLAGE, SEZ, MYLASANDRA, BENGALURU 560059",
    "code": "INKGG6"
  },
  {
    "name": "BAGMANE DEVELOPERS SEZ II, RAMAN NAGAR, BENGALURU",
    "code": "INKJB6"
  },
  {
    "name": "CESSNA BUSINESS PARK SEZ BELLANDUR BENGALURU560037",
    "code": "INBLC6"
  },
  {
    "name": "WIPRO LIMITED, SARJAPUR, BENGALURU- 560035",
    "code": "INCRW6"
  },
  {
    "name": "KEONICS, SEZ, SHIMOGA, KARNATAKA 560001",
    "code": "INSMK6"
  },
  {
    "name": "WIPRO LIMITED SEZ, ELEC CITY, BENGALURU 560100",
    "code": "INSBW6"
  },
  {
    "name": "GOPALAN ENTERPRISES SEZ, HOODI, BENGALURU- 560048",
    "code": "INKJG6"
  },
  {
    "name": "INFOSYS LTD SEZ, BANTWAL, MANGALORE - 574153",
    "code": "INMAI6"
  },
  {
    "name": "INFOSYS TECH LTD SEZ, HEBBAL, MYSORE, KARNATAKA",
    "code": "INHEI6"
  },
  {
    "name": "MANYATA EMBASSY BUSINESS PARK SEZ, HOBLI BENGALURU",
    "code": "INHEM6"
  },
  {
    "name": "PRIMAL PROJECTS LTD SEZ, VARTHUR, BENGALURU 560037",
    "code": "INBCP6"
  },
  {
    "name": "ITPL, SEZ, WHITEFIELD ROAD, BENGALURU 560066",
    "code": "INWFI6"
  },
  {
    "name": "LARSEN AND TOUBRO SEZ, HEBBAL, MYSORE",
    "code": "INMYL6"
  },
  {
    "name": "RMZ ECOWORLD INFRASTRUCTURE SEZ, BENGALURU 560103",
    "code": "INKJA6"
  },
  {
    "name": "Suncity SEZ/Gurgaon",
    "code": "INGGS6"
  },
  {
    "name": "GURGAON INFOSPACE LTD. SEZ, DUNDAHERA, GURUGRAM",
    "code": "INGGI6"
  },
  {
    "name": "Reliance SEZ/Gurgaon",
    "code": "INGRN6"
  },
  {
    "name": "ASF INSIGNIA LTD. SEZ, GWAL PAHARI SOHNA, GURUGRAM",
    "code": "INGHC6"
  },
  {
    "name": "Sunwise SEZ/Gurgaon",
    "code": "INGGP6"
  },
  {
    "name": "Ansal SEZ/Sonepat",
    "code": "INSNA6"
  },
  {
    "name": "Ansal SEZ/Gurgaon",
    "code": "INGAS6"
  },
  {
    "name": "ITPG DEVELOPERS PVT. LTD. SEZ, BEHRAMPUR, GURUGRAM",
    "code": "INGRL6"
  },
  {
    "name": "CANDOR GURGAONONE REALTY PROJECTSEZ TIKRI GURUGRAM",
    "code": "INGGU6"
  },
  {
    "name": "Mippl SEZ/Gurgaon",
    "code": "INGGM6"
  },
  {
    "name": "MAYAR INFRASTRUCTURE DEVELOPMENT PVT. LTD.",
    "code": "INGMI6"
  },
  {
    "name": "MAYAR INFRASTRUCTURE DEVELOPMENT PVT. LTD. RAHKA AND NIMOTH VILLAGES",
    "code": "INGID6"
  },
  {
    "name": "Raheja SEZ/Gurgaon",
    "code": "INGRS6"
  },
  {
    "name": "Mittal SEZ/Panipat",
    "code": "INPNI6"
  },
  {
    "name": "SBPL SEZ/Gurgaon",
    "code": "INGGB6"
  },
  {
    "name": "Aepl SEZ/Gurgaon",
    "code": "INGGE6"
  },
  {
    "name": "Perpetual SEZ/Faridabad",
    "code": "INFBP6"
  },
  {
    "name": "ANANT RAJ INDUSTRIES LIMITED",
    "code": "INSNR6"
  },
  {
    "name": "Progressive SEZ/Gurgaon",
    "code": "INGPB6"
  },
  {
    "name": "MIKADO REALTORS LTD SEZ BEHRAMPUR-BALOLA, GURUGRAM",
    "code": "INMKD6"
  },
  {
    "name": "Espire SEZ/Faridabad",
    "code": "INFBE6"
  },
  {
    "name": "Orient SEZ/Gurgaon",
    "code": "INGGC6"
  },
  {
    "name": "QUARKCITY INDIA LTD SEZ PH-VIII EXTN MOHALI PUNJAB",
    "code": "INCDQ6"
  },
  {
    "name": "SUTHERLAND GLOBAL SERVICES SEZ, ERNAKULAM - 682030",
    "code": "INKLG6"
  },
  {
    "name": "INFOPARK PHASE - I, KAKKANAD, KOCHI, KERALA 682042",
    "code": "INKLI6"
  },
  {
    "name": "CARBORUNDUM UNIVERSAL EMD SEZ KALAMASERY ERNACULAM",
    "code": "INKLC6"
  },
  {
    "name": "KSITIL, SEZ, CHERTHALA, ALAPPUZHA 683515",
    "code": "INSRK6"
  },
  {
    "name": "KSITIL, NELLIKODE, KOZHIKODE, KERALA- 673012",
    "code": "INCLK6"
  },
  {
    "name": "GTV TECH SEZ PVTLTD. GHAMROJ SOHNA GURUGRAM 122102",
    "code": "INGGF6"
  },
  {
    "name": "DLF LTD. SEZ, SILOKHERA, GURUGRAM, HARYANA",
    "code": "INGGD6"
  },
  {
    "name": "DLF CYBER CITY DEVELOPERS LTD SEZ GURUGRAM HARYANA",
    "code": "INGDL6"
  },
  {
    "name": "SELECTO SYSTEMS PVT. LTD",
    "code": "INFBS6"
  },
  {
    "name": "Luxor SEZ/Gurgaon",
    "code": "INGGL6"
  },
  {
    "name": "Orient Craft SEZ/Gurgaon",
    "code": "INGGO6"
  },
  {
    "name": "GHI SEZ/Gurgaon",
    "code": "INGGG6"
  },
  {
    "name": "METRO VALLEY BUSINESS PARK PRIVATE LTD.",
    "code": "INFBM6"
  },
  {
    "name": "IT/ITES SEZ/KALAMBOLI",
    "code": "INKLN6"
  },
  {
    "name": "J. MATADEE FREE TRADE ZONE SEZ MANNUR TAMILNADU",
    "code": "INCJJ6"
  },
  {
    "name": "SURAT APPAREL PARK SEZ VANZ, SACHIN, SURAT 394230",
    "code": "INSCH6"
  },
  {
    "name": "Unitech Infra SEZ/Noida",
    "code": "INDEU6"
  },
  {
    "name": "Perfect SEZ/Noida",
    "code": "INPSN6"
  },
  {
    "name": "Jubilant SEZ/Noida",
    "code": "INDEJ6"
  },
  {
    "name": "Gallant SEZ/Noida",
    "code": "INDGI6"
  },
  {
    "name": "OXYGEN BUSINESS PARKS LTD. SEZ, SEC 144, NOIDA, UP",
    "code": "INDEA6"
  },
  {
    "name": "Unitech Hi-Tech SEZ/Noida",
    "code": "INDET6"
  },
  {
    "name": "SMRTPL SEZ/Noida",
    "code": "INDSM6"
  },
  {
    "name": "IVR SEZ/Noida",
    "code": "INDEI6"
  },
  {
    "name": "GOLDEN TOWER INFRATECH SEZ, SECTOR 144, NOIDA, UP",
    "code": "INDGT6"
  },
  {
    "name": "Hari SEZ/Varanasi",
    "code": "INBCH6"
  },
  {
    "name": "RCIPL SEZ/Noida",
    "code": "INDRC6"
  },
  {
    "name": "MIDC AURANGABAD SEZ, SHENDRE, AURANGABAD, MAH",
    "code": "INAWM6"
  },
  {
    "name": "MIDC NANDED SEZ, KRUSHNOOR, NAIGAON, NANDED, MAH.",
    "code": "INDID6"
  },
  {
    "name": "MIDC SEZ PUNE, HINJAWADI, PHASE-III, PUNE",
    "code": "INPUM6"
  },
  {
    "name": "NMSPL SEZ/Raigad",
    "code": "INKLE6"
  },
  {
    "name": "MIDC SATARA SEZ, KESURDE, SATARA, MAH.",
    "code": "INSTU6"
  },
  {
    "name": "INDIABULLS INDUSTRIAL INFRASTRUCTURE LIMITED",
    "code": "INNKI6"
  },
  {
    "name": "MIDC PHALTAN SEZ, MAHARASTRA",
    "code": "INSTM6"
  },
  {
    "name": "THE MANJRI STUD FARM LTD SEZ, HAVELI, PUNE, MAH.",
    "code": "INPNU6"
  },
  {
    "name": "WOCKHARDT INFRAST DEVELOP. SEZ SHENDRE, AURANGABAD",
    "code": "INAWW6"
  },
  {
    "name": "MANGALORE SEZ, BAIKAMPADI, DAKSHINA KANNADA, KAR.",
    "code": "INMAQ6"
  },
  {
    "name": "VILL.KATTUPALLI,TAL.PONNERI,DIST.TIRUVELLORE601120",
    "code": "INKAT1"
  },
  {
    "name": "CHANDIGARH ADMINISTRATION SEZ RGCTP -I, CHANDIGARH",
    "code": "INCDD6"
  },
  {
    "name": "SUN PHARMACEUTICAL IND SEZ FOCALPOINT MOHALI160059",
    "code": "INCDR6"
  },
  {
    "name": "Mahindra SEZ/Jaipur",
    "code": "INJPM6"
  },
  {
    "name": "Somani SEZ/Bhiwadi",
    "code": "INAWS6"
  },
  {
    "name": "Vatika SEZ/Jaipur",
    "code": "INJPV6"
  },
  {
    "name": "Genpect SEZ/Jaipur",
    "code": "INJGI6"
  },
  {
    "name": "RNBIPL SEZ/Bikaner",
    "code": "INBRI6"
  },
  {
    "name": "MAHINDRA WORLD CITY (JAIPUR) LTD., JAIPUR - 302027",
    "code": "INJPW6"
  },
  {
    "name": "MWCL SEZ/Jaipur",
    "code": "INJPC6"
  },
  {
    "name": "Mahindra World SEZ/Jaipur",
    "code": "INJMW6"
  },
  {
    "name": "ANSAL IT CITY & PARKS LTD SEZ TECHZONE GR NOIDA UP",
    "code": "INDIT6"
  },
  {
    "name": "MOSER BAER INDIA LTD",
    "code": "INDEM6"
  },
  {
    "name": "COFORGE LTD. SEZ, TECH ZONE, ITES PARK GR NOIDA UP",
    "code": "INDEN6"
  },
  {
    "name": "WIPRO LTD SEZ, K P - IV, GR. NOIDA, G B NAGAR, UP",
    "code": "INDEW6"
  },
  {
    "name": "HCL TECHNOLOGIES LTD. SEZ, SECTOR 126, NOIDA, UP",
    "code": "INDEH6"
  },
  {
    "name": "OSE SEZ/Noida",
    "code": "INNGO6"
  },
  {
    "name": "SEAVIEW DEVELOPERS LTD. SEZ SECTOR 135, NOIDA, UP",
    "code": "INDES6"
  },
  {
    "name": "KHED ECONOMIC INFRASTRUCTURE SEZ, KHED, PUNE",
    "code": "INTGN6"
  },
  {
    "name": "KUMAR BUILDERS TOWNSHIP VENTURES PVT. LTD.",
    "code": "INPUN6"
  },
  {
    "name": "QUBIX BUSINESS PARK SEZ, HINJAWADI, MULSHI, PUNE",
    "code": "INPNE6"
  },
  {
    "name": "QBP/PUNE",
    "code": "INCCQ"
  },
  {
    "name": "Haldia",
    "code": "INHAL1"
  },
  {
    "name": "ICD KOTTAYAM, VILLAGE NATTAKAM, KOTTAYAM, KERALA",
    "code": "INKYM6"
  },
  {
    "name": "CRYSTAL IT PARK SEZ, KHANDWA ROAD, INDORE - 452001",
    "code": "ININB6"
  },
  {
    "name": "ICD TARAPUR, MAHAGAON, TARAPUR,THANE, MAHARASHTRA",
    "code": "INBNG6"
  },
  {
    "name": "MIHAN SEZ, MIHAN, NAGPUR, MAH.",
    "code": "INKRM6"
  },
  {
    "name": "MINDSPACE BUSINESS PARKS SEZ (SPPL), NAVI MUMBAI",
    "code": "INAIR6"
  },
  {
    "name": "CANDOR ONE HTSPL SEZ, NORTH 24 PARGANA- 700156",
    "code": "INBNX6"
  },
  {
    "name": "TCS LTD., SEZ, NEW TOWN KOLKATA - 700160",
    "code": "INBNT6"
  },
  {
    "name": "DLF IT/ITES SEZ RAJARHAT, KOLKATA-700156",
    "code": "INBXR6"
  },
  {
    "name": "IDCO IT/ITES SEZ, BHUBANESWAR, ODISHA- 751024",
    "code": "INBBS6"
  },
  {
    "name": "AQUALINE PROPERTIES SEZ, KOBA, GANDHINAGAR 382425",
    "code": "INGNA6"
  },
  {
    "name": "GIFT MULTI-SERVICES SEZ, GIFT CITY, GANDHINAGAR",
    "code": "INGNC6"
  },
  {
    "name": "GIGAPLEX ESTATE P LTD SEZ, AIROLI-DIGHE, THANE MAH",
    "code": "INAIG6"
  },
  {
    "name": "PANCHI GUJARA, TEHSIL-GANNUR- SONEPAT DIST HR",
    "code": "INBDM6"
  },
  {
    "name": "LONI-1 ICD GHAZIABAD",
    "code": "INNOI6"
  },
  {
    "name": "KOLKATA IT PARK SEZ, SOUTH 24 PARGANA- W.B. 743502",
    "code": "INBNK6"
  },
  {
    "name": "WIPRO LTD SEZ, SALTLAKE, KOLKATA- 700091",
    "code": "INBNW6"
  },
  {
    "name": "IMPETUS INFOTECH LTD. SEZ, BADIYAKIMA INDORE, M.P.",
    "code": "ININI6"
  },
  {
    "name": "INFOSYS LTD. SEZ, TIGARIYA BADSHAH, INDORE, M.P.",
    "code": "ININN6"
  },
  {
    "name": "CHANDIGARH ADMINISTRATION SEZ RGCTP-II, CHANDIGARH",
    "code": "INCDC6"
  },
  {
    "name": "SUNSTREAM CITY P LTD SEZ MULUND, SUBURBAN MUMBAI",
    "code": "INMUC6"
  },
  {
    "name": "SYNTEL INTERNATIONAL SEZ TALWADE SOFTWAREPARK PUNE",
    "code": "INPSI6"
  },
  {
    "name": "MAGARPATTA CITY MTDCCL SEZ, HADAPSAR HAVELI, PUNE",
    "code": "INPMT6"
  },
  {
    "name": "INFOSYS TECHNOLOGIES I, SEZ, MULSHI, PUNE, MAH.",
    "code": "INPIT6"
  },
  {
    "name": "EON KHARADI INFRASTRUCTURE SEZ PHASE I, PUNE, MAH.",
    "code": "INPEK6"
  },
  {
    "name": "ICD THIMMAPUR, 11-60/5-7, THIMMAPUR, 509325, AP",
    "code": "INTMX6"
  },
  {
    "name": "LANCO SOLAR PVT LTD",
    "code": "INRJN6"
  },
  {
    "name": "HAZIRA PORT, CHORYASHI, BYPASS RD., HAZIRA, SURAT",
    "code": "INHZA1"
  },
  {
    "name": "DEEMED",
    "code": "DEEMED"
  },
  {
    "name": "KRIBHCO LOGISTICS PARK, REWARI, HARYANA",
    "code": "INPKR6"
  },
  {
    "name": "ICD WARDHA, BHUGAON LINK ROAD, WARDHA, MAHARASHTRA",
    "code": "INCHJ6"
  },
  {
    "name": "PCCCC,BANDRA KURLA COMPLEX,BANDRA(E),MUMBAI,400051",
    "code": "INDPC4"
  },
  {
    "name": "ICD KALINGANAGAR,KHURUNTI,KIC,JAJPUR,ODISHA 755026",
    "code": "INSKD6"
  },
  {
    "name": "WPCL/CHANDRAPUR",
    "code": "INWPR6"
  },
  {
    "name": "WIPRO LIMITED SEZ -1, HINJAWADI, PUNE, MAH.",
    "code": "INCCW6"
  },
  {
    "name": "CONCOR, SHEETALPUR VILL, BADDI, H.P.173205",
    "code": "INBDI6"
  },
  {
    "name": "PLOT 53, SIPCOT IND. COMPLEX, PHASE-1,HOSUR-635126",
    "code": "INHSU6"
  },
  {
    "name": "IGGSL SEZ/THANE",
    "code": "INALL6"
  },
  {
    "name": "PALLITHOTTAM P.O. KOLLAM, KERALA 691006",
    "code": "INKUK1"
  },
  {
    "name": "ELCOT SEZ, NAVALPATTU, TIRUCHIRAPPALLAI - 620026",
    "code": "INTPJ6"
  },
  {
    "name": "ELCOT SEZ, HOSUR, KRISHNAGIRI - 635109",
    "code": "INHSA6"
  },
  {
    "name": "GATEWAY OFFICE PARKS SEZ PERUNGULATHUR CHENNAI 63",
    "code": "INTBP6"
  },
  {
    "name": "KGISL SEZ, SARAVANAMPATTI, COIMBATORE - 641035",
    "code": "INCBC6"
  },
  {
    "name": "NEWCHENNAI TOWNSHIP MULTISERVICESEZ SEEKINANKUPPAM",
    "code": "INCJC6"
  },
  {
    "name": "SESA STERLITE LIMITED",
    "code": "INTNS6"
  },
  {
    "name": "VVM SEZ/ Tiruneveli",
    "code": "INTEV6"
  },
  {
    "name": "JGHIPL SEZ/ Sriperumbudur",
    "code": "INCJG6"
  },
  {
    "name": "KIDAB TEXTILES SEZ HASSAN, UTTAR KANNADA KARNATAKA",
    "code": "INHST6"
  },
  {
    "name": "MIDC IND.AREA, BUTIBORI, NAGPUR, MH 441122",
    "code": "INNGB6"
  },
  {
    "name": "ICD KANECH, SAHNEWAL, LUDHIANA",
    "code": "INSNI6"
  },
  {
    "name": "ICD CHAWAPAYAL, VILL. CHAWA, TEHSIL SAMRALA",
    "code": "INCPR6"
  },
  {
    "name": "TRIL INFOPARK LTD SEZ RG SALAI OMR TARAMANI 600113",
    "code": "INMAS6"
  },
  {
    "name": "DLF INFOCITY CHENNAI LTD SEZ, RAMAPURAM CHENNAI 89",
    "code": "INCJD6"
  },
  {
    "name": "TCS SEZ, NAVALLUR, SIRUSERI 603103",
    "code": "INTBT6"
  },
  {
    "name": "ARTHA INFRATECH LTD SEZ, TZ-IV, GR NOIDA G B NAGAR",
    "code": "INDAR6"
  },
  {
    "name": "JUBILIANT SEZ, VILAYAT, VAGRA, BHARUCH, GUJ 392012",
    "code": "INBHC6"
  },
  {
    "name": "GULF OIL SEZ, YELAHANKA HOBLI, BENGALURU",
    "code": "INHEB6"
  },
  {
    "name": "KSITIL, SEZ, KORATTY, THRISSUR, KERALA - 682030",
    "code": "INKNK6"
  },
  {
    "name": "TATA CONSULTANCY SERVICES SEZ BADA BANGARDA INDORE",
    "code": "ININT6"
  },
  {
    "name": "ELCOT IT PARK SEZ, GANGAIKONDAN, TIRUNELVELI",
    "code": "INMAE6"
  },
  {
    "name": "HEXAWARE TECHNOLOGIES SEZ NAVALLUR SIRUSERI 603103",
    "code": "INTBS6"
  },
  {
    "name": "KRIBHCO INFSTR LTD,HAZIRA,KRIBHCO NGR,SURAT,GUJRAT",
    "code": "INKBC6"
  },
  {
    "name": "WARDHA POWER COMPANY PVT. LTD SEZ",
    "code": "INWRR6"
  },
  {
    "name": "QUADRON BUSINESS PARK SEZ HINJEWADI PHASE-II, PUNE",
    "code": "INCCQ6"
  },
  {
    "name": "OPGS INFRASTRUCTURE PVT. LTD.",
    "code": "INGAO6"
  },
  {
    "name": "KANDLA SPECIAL ECONOMIC ZONE GHANDHIDHAM 370203",
    "code": "INKDL6"
  },
  {
    "name": "TATA CONSULTANCY SERVICESEZ ADIBATLA HYDERABAD- 510",
    "code": "INURT6"
  },
  {
    "name": "TATA CONSULTANCY SERVICESEZ GACHIBOWLI HYDERABAD32",
    "code": "INLPC6"
  },
  {
    "name": "NSL SEZ PVT LTD (HYD), IDA, UPPAL HYDERABAD 500039",
    "code": "INKCG6"
  },
  {
    "name": "SARAF AGENCIES PVT LTD SEZ, GANJAM, ODISHA 761020",
    "code": "INCAS6"
  },
  {
    "name": "PLOT-1 SECTOR 9 GROWTH CENTRE BAWAL REWARI HARYANA",
    "code": "INBAW6"
  },
  {
    "name": "IDCO IT KNOWLEDGEPARK SEZ, KHURDA B'NESHWAR 752054",
    "code": "INKUR6"
  },
  {
    "name": "DAHEJ SEZ, TALUKA-VAGRA, BHARUCH, GUJARAT",
    "code": "INBHD6"
  },
  {
    "name": "ZYDUS INFRASTRUCTURE PVT LTD, SEZ, AHMEDABAD",
    "code": "INZIP6"
  },
  {
    "name": "ICD TUMB, TALUK UMBERGAON, DIST VALSAD, GUJARAT",
    "code": "INSAJ6"
  },
  {
    "name": "Hindaun ICD/Karauli",
    "code": "INHAN6"
  },
  {
    "name": "ICD PALWAL, VILL-JANOULI-BAGHOLA, HARYANA -121102",
    "code": "INPWL6"
  },
  {
    "name": "SURAT HIRA BOURSE, KATARGAM, SURAT-395008 GUJRAT",
    "code": "INHIR6"
  },
  {
    "name": "VEDANTA LTD. SEZ, JHARSUGUDA, ORISSA- 768201",
    "code": "INJHV6"
  },
  {
    "name": "ICD POWARKHEDA, BIAORA, DIST HOSHANGABAD, M.P.",
    "code": "INPRK6"
  },
  {
    "name": "ICD, GRFL, SAHNEWAL, LUDHIANA, PUNJAB",
    "code": "INSGF6"
  },
  {
    "name": "ICD, PSWC, DHANDARI KALAN, LUDHIANA, PUNJAB",
    "code": "INDDL6"
  },
  {
    "name": "CONCOR ICD, MOUZA-BAMPADA, REMUNA, BALASORE- 756056",
    "code": "INBLE6"
  },
  {
    "name": "ICD JATTIPUR, SAMALKHA TEHSIL-PANIPAT DIST HARYANA",
    "code": "INDWN6"
  },
  {
    "name": "BIOCON SEZ, BOMMASANDRA, BANGALORE 5600099",
    "code": "INSBC6"
  },
  {
    "name": "ICD BORKHEDI, DIST-NAGPUR, MAHARASHTRA",
    "code": "INBOK6"
  },
  {
    "name": "ICD, KIFTPL KASHIPUR, US NAGAR-244713 UTTARAKHAND",
    "code": "INHPI6"
  },
  {
    "name": "ICD KATHUWAS, MADHAN VILL, DIST ALWAR, RAJASTHAN",
    "code": "INCML6"
  },
  {
    "name": "NEWFOUND PROPERTIES AND LEASING PVT. LTD",
    "code": "INJNJ6"
  },
  {
    "name": "LOMA CO-DEVELOPERS 1 SEZ, GHANSOLI, NAVI MUMBAI",
    "code": "INGNL6"
  },
  {
    "name": "PERSIPINA DEVELOPERS LTD SEZ PANVEL RAIGARH, MAH",
    "code": "INPNL6"
  },
  {
    "name": "AEQUS SEZ PVT LTD, BELGAUM- 591243",
    "code": "INBGQ6"
  },
  {
    "name": "ICD PANTNAGAR, UTTARAKHAND",
    "code": "INHDD6"
  },
  {
    "name": "VILLAGE IBRAHIMBUR, POST KHURJA, BULANDSHAHR, UP",
    "code": "INAIK6"
  },
  {
    "name": "KIADB FOOD PROCESSING SPECIAL ECONOMIC ZONE",
    "code": "INHSF6"
  },
  {
    "name": "KIDAB PHARMACEUTICAL SEZ, HASAN, KARNATAKA",
    "code": "INHSP6"
  },
  {
    "name": "KBITS-SEZ/BANGALORE",
    "code": "INBNC6"
  },
  {
    "name": "PUTHUVYPEEN SEZ, ERNAKULAM, KERALA",
    "code": "INERP6"
  },
  {
    "name": "VALLARPADOM SEZ, ERNAKULAM KERALA - 682009",
    "code": "INERV6"
  },
  {
    "name": "KINFRA FILM & VIDEO PARK, SEZ, KAZHAKUTTAM 695585",
    "code": "INTVC6"
  },
  {
    "name": "KINFRA FOOD PRO SEZ, KAKKANCHERRY KOZHIKODE 673635",
    "code": "INCCT6"
  },
  {
    "name": "TATA STEEL LTD. SEZ, GANJAM, ODISHA - 761020",
    "code": "INCAG6"
  },
  {
    "name": "L&T SHIPBUILDING LTD SEZ KATTUPALLI CHENNAI 600120",
    "code": "INTLT6"
  },
  {
    "name": "HCL IT CITY LUCKNOW SEZ CHACK GAJARIA FARM LUCKNOW",
    "code": "INLCH6"
  },
  {
    "name": "ICD SACHANA, CWC(N),TK VIRAMGAM, AHMEDABAD,GUJARAT",
    "code": "INJKA6"
  },
  {
    "name": "M/S. G. P. REALTORS PVT. LTD.",
    "code": "INGNP6"
  },
  {
    "name": "Agra",
    "code": "INAGR6"
  },
  {
    "name": "Agartala",
    "code": "INAGT8"
  },
  {
    "name": "Aizwal",
    "code": "INAJL4"
  },
  {
    "name": "Ahmedabad ICDS",
    "code": "INAMD6"
  },
  {
    "name": "Amritsar",
    "code": "INATQ6"
  },
  {
    "name": "Attari Road",
    "code": "INATR8"
  },
  {
    "name": "Vadodara",
    "code": "INBDQ1"
  },
  {
    "name": "Bhopal",
    "code": "INBHO4"
  },
  {
    "name": "Bhavanagar",
    "code": "INBHU4"
  },
  {
    "name": "Bangalore",
    "code": "INBLR6"
  },
  {
    "name": "Bolanganj",
    "code": "INBOL8"
  },
  {
    "name": "FPO, MUMBAI CUSTOMS ZONE-1 BALLARD ESTATE 400001",
    "code": "INBOM5"
  },
  {
    "name": "AIRPORT PARCEL SORTING SPEED POST MUMBAI-400099",
    "code": "INBPS5"
  },
  {
    "name": "SEA PORT BUDGE BUDGE",
    "code": "INBUD1"
  },
  {
    "name": "Carijam",
    "code": "INCAR1"
  },
  {
    "name": "Changrabandh",
    "code": "INCBD8"
  },
  {
    "name": "Chandbali",
    "code": "INCBL1"
  },
  {
    "name": "3RD FLOOR, FPO, 12, RAY ROAD KOLKATA, 700001",
    "code": "INCCU5"
  },
  {
    "name": "Coimbatore",
    "code": "INCJB6"
  },
  {
    "name": "Cocochel",
    "code": "INCOL1"
  },
  {
    "name": "Daparizo",
    "code": "INDAE4"
  },
  {
    "name": "Daman",
    "code": "INDAM4"
  },
  {
    "name": "Dhanbad",
    "code": "INDBD4"
  },
  {
    "name": "Daulatabad ICD",
    "code": "INDCB6"
  },
  {
    "name": "Dehra Dun",
    "code": "INDED4"
  },
  {
    "name": "FPO, KOTLA ROAD NEW DELHI-110002",
    "code": "INDEL5"
  },
  {
    "name": "Deparzio",
    "code": "INDEP4"
  },
  {
    "name": "Diu",
    "code": "INDIU1"
  },
  {
    "name": "Diu",
    "code": "INDIU4"
  },
  {
    "name": "Dabolim",
    "code": "INDRL1"
  },
  {
    "name": "Dwarka",
    "code": "INDWA1"
  },
  {
    "name": "Faridabad",
    "code": "INFBD3"
  },
  {
    "name": "Gauhati (Panidi)",
    "code": "INGAU1"
  },
  {
    "name": "Guwahati",
    "code": "INGAW2"
  },
  {
    "name": "Gurgaon",
    "code": "INGGN2"
  },
  {
    "name": "Gurgaon",
    "code": "INGGN3"
  },
  {
    "name": "Ghojadanga",
    "code": "INGJX8"
  },
  {
    "name": "Gorakhpur",
    "code": "INGOP4"
  },
  {
    "name": "Guntur",
    "code": "INGTR2"
  },
  {
    "name": "Guntur",
    "code": "INGTR3"
  },
  {
    "name": "Gwalior",
    "code": "INGWL4"
  },
  {
    "name": "Hubli",
    "code": "INHBX4"
  },
  {
    "name": "Hilli",
    "code": "INHLI8"
  },
  {
    "name": "Hissar",
    "code": "INHSS4"
  },
  {
    "name": "Hyderabad",
    "code": "INHYD3"
  },
  {
    "name": "TS- HYB-48 FPO HUMAYUN NAGAR, TELANGANA-500028",
    "code": "INHYD5"
  },
  {
    "name": "Hyderabad",
    "code": "INHYD6"
  },
  {
    "name": "NASIK ICDS",
    "code": "INISK4"
  },
  {
    "name": "Nasik",
    "code": "INISK6"
  },
  {
    "name": "Chandigarh",
    "code": "INIXC4"
  },
  {
    "name": "Allahabad",
    "code": "INIXD4"
  },
  {
    "name": "MANGALORE AIR CARGO, KARNATAKA",
    "code": "INIXE4"
  },
  {
    "name": "Belgaum",
    "code": "INIXG4"
  },
  {
    "name": "LiAgencyari",
    "code": "INIXI4"
  },
  {
    "name": "Jammu",
    "code": "INIXJ4"
  },
  {
    "name": "Keshod",
    "code": "INIXK4"
  },
  {
    "name": "MADURAI AIR CARGO COMPLEX, MADURAI, TAMIL NADU",
    "code": "INIXM4"
  },
  {
    "name": "AURANGABAD",
    "code": "INIXU4"
  },
  {
    "name": "Jamshedpur",
    "code": "INIXW4"
  },
  {
    "name": "Kandla",
    "code": "INIXY4"
  },
  {
    "name": "Jayanagar",
    "code": "INJAY8"
  },
  {
    "name": "Jogbani",
    "code": "INJBN8"
  },
  {
    "name": "Jodhpur",
    "code": "INJDH4"
  },
  {
    "name": "Jodhpur",
    "code": "INJDH6"
  },
  {
    "name": "JAMNAGAR AIR CARGO, GUJARAT",
    "code": "INJGA4"
  },
  {
    "name": "Jaigad Port",
    "code": "INJGD6"
  },
  {
    "name": "Jhulaghat(Pithoragarh)",
    "code": "INJHO8"
  },
  {
    "name": "Jaigaon",
    "code": "INJIG8"
  },
  {
    "name": "Jabalpur",
    "code": "INJLR4"
  },
  {
    "name": "Jarwa",
    "code": "INJWA8"
  },
  {
    "name": "Kakinada",
    "code": "INKAK6"
  },
  {
    "name": "Kohlapur",
    "code": "INKLH3"
  },
  {
    "name": "Lucknow",
    "code": "INKLO4"
  },
  {
    "name": "POSTAL APPRAISING DEPT. 62/4835-A KERALA-682011",
    "code": "INKOC5"
  },
  {
    "name": "Kota",
    "code": "INKTU6"
  },
  {
    "name": "Kundla",
    "code": "INKUN3"
  },
  {
    "name": "Malda",
    "code": "INLDA4"
  },
  {
    "name": "Latu Bazar",
    "code": "INLTB8"
  },
  {
    "name": "Ludhiana",
    "code": "INLUD6"
  },
  {
    "name": "Ludhiana",
    "code": "INLUH4"
  },
  {
    "name": "FPO LUDHIANA",
    "code": "INLUH5"
  },
  {
    "name": "Ludhiana",
    "code": "INLUH6"
  },
  {
    "name": "INTERNATIONAL BUSINESS CNTR FP CHENNAI, 600016",
    "code": "INMAA5"
  },
  {
    "name": "Mahe",
    "code": "INMAH1"
  },
  {
    "name": "ICD KERN, ARUPPUKOTTAI, MADURAI, TAMIL NADU",
    "code": "INMDU6"
  },
  {
    "name": "Meerut",
    "code": "INMER3"
  },
  {
    "name": "Mohali",
    "code": "INMHI3"
  },
  {
    "name": "Mohanbari",
    "code": "INMOH4"
  },
  {
    "name": "Moradabad",
    "code": "INMOR2"
  },
  {
    "name": "Moradabad",
    "code": "INMOR3"
  },
  {
    "name": "Margao",
    "code": "INMRG4"
  },
  {
    "name": "MULUND ICDS",
    "code": "INMUL3"
  },
  {
    "name": "Murad",
    "code": "INMUR1"
  },
  {
    "name": "Mysore",
    "code": "INMYQ4"
  },
  {
    "name": "Tuglakabad",
    "code": "INNDP1"
  },
  {
    "name": "Nepalgunj Road",
    "code": "INNGR8"
  },
  {
    "name": "Village Namgaya Shipkila",
    "code": "INNGS8"
  },
  {
    "name": "Namkhana",
    "code": "INNKN8"
  },
  {
    "name": "Neamati Steamer Ghat",
    "code": "INNMT8"
  },
  {
    "name": "Nampong",
    "code": "INNPG8"
  },
  {
    "name": "Nagpur",
    "code": "INNPR3"
  },
  {
    "name": "Panipat",
    "code": "INPAP2"
  },
  {
    "name": "Panipat",
    "code": "INPAP3"
  },
  {
    "name": "Pipavav (Victor) Port",
    "code": "INPAV2"
  },
  {
    "name": "Pipavav (Victor) Port",
    "code": "INPAV3"
  },
  {
    "name": "Porbandar",
    "code": "INPBD4"
  },
  {
    "name": "Pantnagar",
    "code": "INPGH4"
  },
  {
    "name": "Pithampur",
    "code": "INPIR3"
  },
  {
    "name": "JAWAHARLAL NEHRU PORT AUTHORITY SEZ, NAVI MUMBAI",
    "code": "INPJN6"
  },
  {
    "name": "Pune",
    "code": "INPNQ2"
  },
  {
    "name": "Pune",
    "code": "INPNQ3"
  },
  {
    "name": "Panitanki (Naxalbari)",
    "code": "INPNT8"
  },
  {
    "name": "Pondicherry",
    "code": "INPNY4"
  },
  {
    "name": "Patparganj",
    "code": "INPPG3"
  },
  {
    "name": "Rajkot",
    "code": "INRAJ4"
  },
  {
    "name": "Balurghat",
    "code": "INRGH4"
  },
  {
    "name": "Raipur",
    "code": "INRPR4"
  },
  {
    "name": "Raipur",
    "code": "INRPR6"
  },
  {
    "name": "Rourkela",
    "code": "INRRK4"
  },
  {
    "name": "Rupsi",
    "code": "INRUP4"
  },
  {
    "name": "Shillang",
    "code": "INSHL4"
  },
  {
    "name": "Singanalur ICDS",
    "code": "INSIL6"
  },
  {
    "name": "Singnallur",
    "code": "INSIR3"
  },
  {
    "name": "Simla",
    "code": "INSLV4"
  },
  {
    "name": "Sonauli",
    "code": "INSNL8"
  },
  {
    "name": "Sholapur",
    "code": "INSSE4"
  },
  {
    "name": "Sutarkandi",
    "code": "INSTR8"
  },
  {
    "name": "Surat",
    "code": "INSTV1"
  },
  {
    "name": "Surat",
    "code": "INSTV4"
  },
  {
    "name": "Salem",
    "code": "INSXV4"
  },
  {
    "name": "Tuglakabad",
    "code": "INTKD9"
  },
  {
    "name": "Tikonia",
    "code": "INTKN8"
  },
  {
    "name": "Tungi",
    "code": "INTNG8"
  },
  {
    "name": "T.T.Shed (Kidderpore)",
    "code": "INTTS8"
  },
  {
    "name": "Tirupur",
    "code": "INTUP3"
  },
  {
    "name": "Udaipur",
    "code": "INUDR4"
  },
  {
    "name": "Udaipur",
    "code": "INUDR6"
  },
  {
    "name": "Secunderabad",
    "code": "INUND3"
  },
  {
    "name": "Vijayawada",
    "code": "INVGA4"
  },
  {
    "name": "Vizag SEZ",
    "code": "INVIZ6"
  },
  {
    "name": "Varanasi",
    "code": "INVNS6"
  },
  {
    "name": "Warrangal",
    "code": "INWGC4"
  },
  {
    "name": "ICD, HEMNAGAR",
    "code": "INHND6"
  },
  {
    "name": "RIICO SEZ - I, SITAPURA, JAIPUR - 302022",
    "code": "INJPI6"
  },
  {
    "name": "BEYPORE PORT, CALICUT, KERALA",
    "code": "INBEY1"
  },
  {
    "name": "AMIN PROPERTIES LLP SEZ DEVENAHALI BENGALURU625398",
    "code": "INDLH6"
  },
  {
    "name": "RGA INFRASTRUCTURE SEZ, VARTHUR, BENGALURU 560035",
    "code": "INCRL6"
  },
  {
    "name": "LAND CUSTOMS STATION - LOKSAN",
    "code": "INCRXB"
  },
  {
    "name": "LCS BIRPARA, SILIGURI, WEST BENGAL",
    "code": "INDLOB"
  },
  {
    "name": "DHAMRA PORT, DOSINGA, BHADRAKH, ODISHA 756171",
    "code": "INDMA1"
  },
  {
    "name": "EMBASSY OFFICE PARKS SEZ, HINJEWADI, MULSHI, PUNE",
    "code": "INCCP6"
  },
  {
    "name": "FESTUS PROPERTIES PVT LTD SEZ (HB), POWAI, MUMBAI",
    "code": "INVKH6"
  },
  {
    "name": "ICD BHAMBOLI-APM, CHAKAN INDUSTRIAL AREA, PUNE",
    "code": "INGRW6"
  },
  {
    "name": "CAPGEMENI TECHNOLOGY SERVICES SEZ AKP NAVI MUMBAI",
    "code": "INAII6"
  },
  {
    "name": "CONCOR ICD, DEBADIH, JHARSUGUDA DISTRICT, ODISHA",
    "code": "INJSG6"
  },
  {
    "name": "LAND CUSTOMS STATION PIPRAUN, BIHAR",
    "code": "INKJIB"
  },
  {
    "name": "GIDC APPAREL PARK SEZ AHMEDABAD",
    "code": "INAPI6"
  },
  {
    "name": "E-COMPLEX SEZ, RAMPARA-II JAFRABAD, AMRELI GUJARAT",
    "code": "INJBL6"
  },
  {
    "name": "LAND CUSTOMS STATION- KAMARDWISA",
    "code": "INPBLB"
  },
  {
    "name": "SPAN VENTURE LTD SEZ, EACHANARI, COIMBATORE- 641021",
    "code": "INCSV6"
  },
  {
    "name": "SANDHYA INFOCITY SEZ, 33OMR NAVALUR CHENNAI 600130",
    "code": "INCGE6"
  },
  {
    "name": "COGNIZANT TECHNOLOGY SOLUTIONS SEZ, CHENNAI 603103",
    "code": "INTBC6"
  },
  {
    "name": "ELECTRONICS CORPORATION OF TAMIL NADU - ELCOT - I MADURAI [ILANDDHAIKULAM]",
    "code": "INMEC6"
  },
  {
    "name": "IG3 INFRA LTD SEZ THORAIPAKKAM, CHENNAI 600097",
    "code": "INCJI6"
  },
  {
    "name": "ELCOT SEZ, VILANKURICHI, COIMBATORE 641014",
    "code": "INCEC6"
  },
  {
    "name": "ESTANCIA IT PARK SEZ, GUDUVANCHERRY CHENNAI 603202",
    "code": "INCJA6"
  },
  {
    "name": "CONCOR ICD- NAYA RAIPUR, CHHATTISGARH-492101",
    "code": "INRML6"
  },
  {
    "name": "CHEYYAR SEZ DEVELOPERS, BARGUR, KRISHNAGIRI- 635304",
    "code": "INKTY6"
  },
  {
    "name": "ADANI ICD KILARAIPUR,DEHLON,LUDHIANA",
    "code": "INQRP6"
  },
  {
    "name": "SIPCOT (ENGINEERING) LTD, SEZ, RANIPET-602403",
    "code": "INVLR6"
  },
  {
    "name": "ELCOT SEZ, SHOLINGANALLUR, TAMBARAM, KANCHIPURAM",
    "code": "INCJE6"
  },
  {
    "name": "ICD VIRAMGAM, BHOJWA, AHMEDABAD, GUJARAT",
    "code": "INVGR6"
  },
  {
    "name": "ITPL SEZ-II / BANAGLORE",
    "code": "INWFT6"
  },
  {
    "name": "SOFTEX",
    "code": "INXXX0"
  },
  {
    "name": "INFOSYS LTD SEZ, SECTOR 83, ALPHA SAS NAGAR MOHALI",
    "code": "INSAS6"
  },
  {
    "name": "WIPRO LTD SEZ, 203, MANIKONDA, R R DISTRICT 500032",
    "code": "INLPW6"
  },
  {
    "name": "SERENE PROPERTIES PRIVATE LIMITED",
    "code": "INGTS6"
  },
  {
    "name": "DIVYASREE NSL INFRA SEZ RAIDURGAM RR DISTRICT TEL",
    "code": "INLPS6"
  },
  {
    "name": "INFOSYS LTD SEZ POCHARAM, MEDCHAL MALKAGIRI 500088",
    "code": "INGTI6"
  },
  {
    "name": "LANCO HILLS TECH PARK SEZ MANIKONDA R R DIST500089",
    "code": "INHYB6"
  },
  {
    "name": "APIIC MULTI PROD SEZ, DWARAKAPURAM, NELLORE 524421",
    "code": "INNYP6"
  },
  {
    "name": "APIIC LTD BUILDING PROD SEZ PRAKASAM ONGOLE 523211",
    "code": "INBMA6"
  },
  {
    "name": "APIIC LTD SEZ HILL NO.3 MADHURAWADA VISAKHAPATNAM",
    "code": "INVSA6"
  },
  {
    "name": "WIPRO LTD SEZ 124/P GOPANAPALLY RANGA REDDY 500019",
    "code": "INLWG6"
  },
  {
    "name": "CCL PRODUCTS SEZ VARADAIAHPALEM CHITTOOR, AP517645",
    "code": "INSPC6"
  },
  {
    "name": "INDU TECHZONE PVT. LTD.",
    "code": "INURI6"
  },
  {
    "name": "NAVAYUGA LEGALA ESTATES PVT LTD",
    "code": "INSNS6"
  },
  {
    "name": "TSIIC SEZ NANAKRAMGUDA, HYDERABAD 500008",
    "code": "INSNN6"
  },
  {
    "name": "CUSTOM HOUSE- T.T SHED (KIDDERPOR), WEST BENGAL",
    "code": "INTTS1"
  },
  {
    "name": "RAIL LINKED ICD- JAJPUR, ODISHA-755026",
    "code": "INJJK6"
  },
  {
    "name": "EURO MULTIVISION LTD. SEZ",
    "code": "INBCO6"
  },
  {
    "name": "INFOSYS SEZ NOIDA",
    "code": "INDEF6"
  },
  {
    "name": "SEZ BIOTECH SERVICES MANJARI BUDRUK, HAVELI, PUNE",
    "code": "INPNB6"
  },
  {
    "name": "LCS LAUKAHA, DIST- MADHUBANI, BIHAR",
    "code": "INLKQB"
  },
  {
    "name": "EON KHARADI INFRASTRUCTURE SEZ PHASE II, PUNE, MAH",
    "code": "INPUE6"
  },
  {
    "name": "CONCOR ICD, MIHAN, NAGPUR",
    "code": "INKPK6"
  },
  {
    "name": "MODINAGAR ICD, NOIDA, UTTAR PRADESH",
    "code": "INMUZ6"
  },
  {
    "name": "LCS SHERATHANG",
    "code": "INNTLB"
  },
  {
    "name": "LAND CUSTOMS STATION, THOOTHIBARI",
    "code": "INNTVB"
  },
  {
    "name": "ELCOT SEZ, JAGIR AMMAPALAYAM, SALEM 636302",
    "code": "INSXE6"
  },
  {
    "name": "PERUNGUDI REAL ESTATE SEZ PERUNGUDI CHENNAI 600096",
    "code": "INPRD6"
  },
  {
    "name": "LAND CUSTOMS STATION, SIKTA",
    "code": "INSTFB"
  },
  {
    "name": "FPO -VARANASI",
    "code": "INVNS5"
  },
  {
    "name": "MANTRI DEVELOPERS SEZ NANAKRAMGUDA RR DIST H'BAD-8",
    "code": "INLPM6"
  },
  {
    "name": "CUSTOM HOUSE-KARIMGANJ STEAMERGHAT & FERRY STATION",
    "code": "INKGJ1"
  },
  {
    "name": "RAIGANJ RAILWAY STATION- SUDARSHANPUR, WEST BENGAL",
    "code": "INRGJ2"
  },
  {
    "name": "ICD BARHI, GANAUR, SONEPAT DISTRICT, HARYANA",
    "code": "INRUG6"
  },
  {
    "name": "FPO-AGRA",
    "code": "INAGR5"
  },
  {
    "name": "FPO-BHOPAL",
    "code": "INBPL5"
  },
  {
    "name": "FPO-SEA CHENNAI",
    "code": "INFCH5"
  },
  {
    "name": "FPO-GUWAHATI",
    "code": "INGAU5"
  },
  {
    "name": "HEMNAGAR LCS- PORT",
    "code": "INHND1"
  },
  {
    "name": "LCS HEMNAGAR",
    "code": "INHNDB"
  },
  {
    "name": "FPO-LEH",
    "code": "INIXL5"
  },
  {
    "name": "LCS KULKULI, KUMARGRAM, ALPIURDUAR - 736205",
    "code": "INKMAB"
  },
  {
    "name": "FPO-KANPUR",
    "code": "INKNU5"
  },
  {
    "name": "LCS KAKRAHWA DISTRICT SIDDHARTH NAGAR 277206",
    "code": "INKWHB"
  },
  {
    "name": "FPO- PATNA",
    "code": "INPNF5"
  },
  {
    "name": "FPO- RANCHI",
    "code": "INRNC5"
  },
  {
    "name": "FPO- RAIPUR",
    "code": "INRPU5"
  },
  {
    "name": "FPO-SRINAGAR",
    "code": "INSXR5"
  },
  {
    "name": "FPO-VIJAYAWADA",
    "code": "INVGA5"
  },
  {
    "name": "BAGMANE DEVELOPERS SEZ III, MARATHAHALLI BENGALURU",
    "code": "INKJM6"
  },
  {
    "name": "BRIGADE PROPERTIES PRIVATE LIMITED",
    "code": "INKJR6"
  },
  {
    "name": "INFOSYS ELECTRONIC CITY",
    "code": "INHLE6"
  },
  {
    "name": "INFOSYS TECHNOLOGIES SEZ HUBLI DHARWAD KARNATAKA",
    "code": "INDWR6"
  },
  {
    "name": "MODERN ASSETS SEZ, YELAHANKAHOBLI BENGALURU 560064",
    "code": "INYNA6"
  },
  {
    "name": "ADANI POWER JHARKHAND LTD SEZ GODDA J'KHAND 814133",
    "code": "INJSM6"
  },
  {
    "name": "HBS SEZ,GIDC, PANOLI, ANKLESHWAR, BHARUCH 394116",
    "code": "INPAO6"
  },
  {
    "name": "INFOSYS LTD SEZ SHOLINGNALLUR, KANCHIPURAM 600119",
    "code": "INTBI6"
  },
  {
    "name": "DELTA ELECTRONICS INDIA SEZ, KURUBARAPALLI-635115",
    "code": "INKML6"
  },
  {
    "name": "NEW CHENNAI TOWNSHIP SEZ(LIGHT ENG) SEEKINANKUPPAM",
    "code": "INCNC6"
  },
  {
    "name": "SNP INFRASTRUCTURE SEZ, PALLAVARAM CHENNAI - 600117",
    "code": "INPVS6"
  },
  {
    "name": "SYNTEL INTERNATIONAL SEZ, NAVALUR, SIRUSERI-603103",
    "code": "INCSP6"
  },
  {
    "name": "TATA CONSULTANCY SERVICES SEZ SECTOR 157, NOIDA UP",
    "code": "INNZM6"
  },
  {
    "name": "KRC INFRA. & PROJECTS GD SEZ, KHARADI HAVELI PUNE",
    "code": "INPUI6"
  },
  {
    "name": "WIPRO LIMITED SEZ -2, HINJEWADI, MULSHI, PUNE",
    "code": "INCCI6"
  },
  {
    "name": "LAXMI INFOBAHN ONE SEZ, KOKAPET, RANGAREDDY- 500057",
    "code": "INLPG6"
  },
  {
    "name": "HCL TECHNOLOGIES SEZ KESARAPALLI KRISHNA AP521102",
    "code": "INBZA6"
  }
]
