// ============================================================================
// Letter of Credit application template — printed from Shipments'
// "Finance This Order" panel. Pure builder so the HTML can be tested.
// ============================================================================

import { colors } from '@theme/index'
import type { CompanyProfile } from '@/types'
import { escapeHtml as esc } from './eu-documents'

export interface LCTemplateForm {
  invoiceValue: string
  buyerName: string
  invoiceRef: string
}

export function buildLCTemplateHtml(
  financeForm: LCTemplateForm,
  companyProfile: Pick<CompanyProfile, 'name' | 'iec' | 'gstin' | 'portOfLoading'>
): string {
  // Same-origin window: every form and company value goes through esc().
  // Only theme colours are written raw.
  return `<!DOCTYPE html>
<html><head><title>Letter of Credit Template</title>
<style>body{font-family:Georgia,serif;max-width:800px;margin:40px auto;padding:0 20px;color:${colors.text}}
h1{font-size:1.4rem;border-bottom:2px solid ${colors.primary};padding-bottom:8px}
.field{border-bottom:1px solid ${colors.textSubtle};min-height:24px;margin:4px 0 16px;padding:4px}
label{font-size:0.75rem;font-weight:600;text-transform:uppercase;letter-spacing:0.5px;color:${colors.textMuted}}
.section{margin:24px 0}.note{font-size:0.8rem;color:${colors.textSubtle};font-style:italic;margin-top:32px;border-top:1px solid ${colors.border};padding-top:12px}
</style></head><body>
<h1>Letter of Credit — Application Template</h1>
<p style="font-size:0.85rem;color:${colors.textMuted}">Complete and submit to your bank. This is a template only — your bank will issue the final LC.</p>
<div class="section">
<label>Applicant (Buyer — opens the LC with their bank)</label><div class="field">${esc(financeForm.buyerName || '_______________')}</div>
</div>
<div class="section">
<label>Beneficiary (Exporter — receives payment)</label><div class="field">${esc(companyProfile.name || '_______________')}</div>
<label>Beneficiary IEC</label><div class="field">${esc(companyProfile.iec || '_______________')}</div>
<label>Beneficiary GSTIN</label><div class="field">${esc(companyProfile.gstin || '_______________')}</div>
<label>LC Amount (USD / INR)</label><div class="field">${esc(financeForm.invoiceValue ? `\u20b9${parseFloat(financeForm.invoiceValue).toLocaleString('en-IN')}` : '_______________')}</div>
<label>Invoice / PO Reference</label><div class="field">${esc(financeForm.invoiceRef || '_______________')}</div>
</div>
<div class="section">
<label>Shipment Terms (Incoterms)</label><div class="field">FOB / CIF / DAP (select applicable)</div>
<label>Latest Shipment Date</label><div class="field">_______________</div>
<label>Expiry Date of LC</label><div class="field">_______________</div>
<label>Port of Loading</label><div class="field">${esc(companyProfile.portOfLoading || '_______________')}</div>
<label>Documents Required</label>
<div class="field">[ ] Commercial Invoice (3 originals)<br>[ ] Packing List<br>[ ] Bill of Lading / Airway Bill<br>[ ] Certificate of Origin (DGFT / Chamber of Commerce)<br>[ ] Phytosanitary / Quality Certificate (if applicable)<br>[ ] Packing Declaration</div>
</div>
<div class="note">Template generated by ComplianceOS. Not a binding legal document. Consult your bank's trade finance team before submission.</div>
</body></html>`
}
