"""Regenerate src/lib/dgft-annexure-data.ts from the DGFT CoO Open API spec.

Source: docs/Certificate+of+Origin+Open+API+v1.0.pdf, section 7 (Annexure).
Tables taken: 7.3 State, 7.4 District, 7.9 UOM, 7.10 Country,
7.11 Domestic Port. Every value is copied from a PDF table cell; the only
change is collapsing whitespace. Nothing is added, renamed or inferred.

What the PDF does NOT have, so this file does not either:
  - codes for states, districts or countries (names only)
  - which state a district or a port belongs to
7.11 Domestic Port is exactly 1,000 rows, the same count at which 7.12
International Port visibly stops mid-alphabet, so treat it as an extract.

    pip install pdfplumber
    python scripts/extract_dgft_annexure.py
"""
import hashlib
import json
import re
from pathlib import Path

import pdfplumber

ROOT = Path(__file__).resolve().parent.parent
PDF = ROOT / 'docs' / 'Certificate+of+Origin+Open+API+v1.0.pdf'
OUT = ROOT / 'src' / 'lib' / 'dgft-annexure-data.ts'

# Section number -> key. Sections in between (7.5-7.8, 7.12) are skipped.
SECTIONS = {'7.3': 'state', '7.4': 'district', '7.5': None, '7.6': None, '7.7': None,
            '7.8': None, '7.9': 'uom', '7.10': 'country', '7.11': 'domestic_port', '7.12': None}
HEADERS = {'Name', 'Value', 'Code(input)', 'Code (Input)'}
FIRST_ANNEXURE_PAGE = 90  # 0-based; section 7 starts on printed page 86


def norm(cell):
    return re.sub(r'\s+', ' ', cell or '').strip()


def extract():
    rows = {k: [] for k in SECTIONS.values() if k}
    current = None
    with pdfplumber.open(PDF) as pdf:
        for page in pdf.pages[FIRST_ANNEXURE_PAGE:]:
            heads = sorted((w['top'], SECTIONS[w['text']]) for w in page.extract_words()
                           if w['text'] in SECTIONS)
            for table in page.find_tables():
                section = current
                for top, key in heads:
                    if top < table.bbox[1]:
                        section = key
                if not section:
                    continue
                for raw in table.extract():
                    cells = [norm(c) for c in raw if norm(c)]
                    if cells and cells[0] not in HEADERS:
                        rows[section].append(cells)
            if heads:
                current = heads[-1][1]
    return rows


def main():
    rows = extract()
    for key, want in (('state', 1), ('district', 1), ('country', 1), ('uom', 2), ('domestic_port', 2)):
        bad = [r for r in rows[key] if len(r) != want]
        if bad:
            raise SystemExit(f'{key}: {len(bad)} rows without {want} cells, e.g. {bad[:3]} - refusing to guess')

    states = [r[0] for r in rows['state']]
    district_rows = [r[0] for r in rows['district']]
    country_rows = [r[0] for r in rows['country']]
    uoms = [{'code': c, 'name': n} for c, n in rows['uom']]
    port_rows = [{'name': n, 'code': c} for n, c in rows['domestic_port']]

    def distinct(values):
        seen, out = set(), []
        for v in values:
            if v.upper() not in seen:
                seen.add(v.upper())
                out.append(v)
        return out

    source = {
        'file': 'docs/' + PDF.name,
        'sha256': hashlib.sha256(PDF.read_bytes()).hexdigest(),
        'rowCounts': {
            'state': len(states), 'district': len(district_rows), 'uom': len(uoms),
            'country': len(country_rows), 'domesticPort': len(port_rows),
        },
    }
    body = [
        '// GENERATED by scripts/extract_dgft_annexure.py - do not edit by hand.',
        f'// Source: {source["file"]}, section 7 (Annexure).',
        '// Every value is a PDF table cell with whitespace collapsed. Rerun the',
        '// script against a new PDF instead of editing this file.',
        '',
        f'export const DGFT_ANNEXURE_SOURCE = {json.dumps(source, indent=2)} as const',
        '',
        '// 7.3 Table State - names only; the PDF gives no state codes.',
        f'export const STATE_NAMES: readonly string[] = {json.dumps(states, indent=2, ensure_ascii=False)}',
        '',
        '// 7.4 Table District - names only, no state column. Names that repeat',
        '// (the same district name in two states) are listed once.',
        f'export const DISTRICT_NAMES: readonly string[] = {json.dumps(distinct(district_rows), indent=2, ensure_ascii=False)}',
        '',
        '// 7.9 UOM Table - "Code(input)" and "Value".',
        f'export const UOM_ROWS: readonly {{ code: string; name: string }}[] = {json.dumps(uoms, indent=2, ensure_ascii=False)}',
        '',
        '// 7.10 Table Country - names only; exact repeats at the end of the table',
        '// are listed once.',
        f'export const COUNTRY_NAMES: readonly string[] = {json.dumps(distinct(country_rows), indent=2, ensure_ascii=False)}',
        '',
        '// 7.11 Table Domestic Port - "Value" and "Code (Input)", every row as',
        '// printed, including the few that are not port codes.',
        f'export const DOMESTIC_PORT_ROWS: readonly {{ name: string; code: string }}[] = {json.dumps(port_rows, indent=2, ensure_ascii=False)}',
        '',
    ]
    OUT.write_text('\n'.join(body), encoding='utf-8', newline='\n')
    print(json.dumps(source['rowCounts']), 'distinct districts', len(distinct(district_rows)),
          'distinct countries', len(distinct(country_rows)))


if __name__ == '__main__':
    main()
