-- Baseline schema, captured from the live project on 23 Sept 2026.
--
-- Why this file exists: until now no tracked migration created companies,
-- shipments, user_profiles, user_settings, api_keys or the other base tables.
-- They were applied by pasting supabase/schema.sql and the loose
-- supabase/migration_*.sql files into the SQL editor by hand, so a fresh
-- project could not be rebuilt -- `supabase db reset` died on the first
-- migration with: relation "public.shipments" does not exist.
--
-- This file is `supabase/db dump --schema public` against the live project,
-- and therefore represents production as it really is, including the seven
-- companies columns (city, state, pin, state_code, port_of_loading, gstin,
-- address) that no file in git ever created. Note `pin` is integer in
-- production, not text.
--
-- The migrations it supersedes are kept for reference under
-- supabase/archive/. Do not edit this file to change the schema; add a new
-- migration after it instead.
--
-- Two objects live outside the `public` schema and so are NOT in the dump:
--   1. the `on_auth_user_created` trigger on auth.users -- re-added at the
--      foot of this file, recovered from supabase/schema.sql. Without it a
--      new signup gets no company, profile or settings row.
--   2. the event trigger driving public.rls_auto_enable(). Event triggers are
--      cluster-level, not schema-scoped. It is a belt-and-braces net that
--      turns RLS on for any future table; every table below already has RLS
--      enabled explicitly, so a rebuild is correct without it. Supabase
--      installs this on new projects itself -- left alone deliberately.




SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE OR REPLACE FUNCTION "public"."cleanup_rate_limits"() RETURNS "void"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  DELETE FROM public.rate_limits WHERE window_date < CURRENT_DATE - INTERVAL '7 days';
END;
$$;


ALTER FUNCTION "public"."cleanup_rate_limits"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."get_user_company_id"() RETURNS "uuid"
    LANGUAGE "sql" STABLE SECURITY DEFINER
    AS $$
  SELECT company_id FROM user_profiles WHERE id = auth.uid()
$$;


ALTER FUNCTION "public"."get_user_company_id"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
DECLARE
  new_company_id UUID;
BEGIN
  -- Create a company for the new user
  INSERT INTO companies (name) VALUES ('My Company')
  RETURNING id INTO new_company_id;

  -- Create user profile linked to the company
  INSERT INTO user_profiles (id, company_id, email, full_name)
  VALUES (
    NEW.id,
    new_company_id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', '')
  );

  -- Create default settings
  INSERT INTO user_settings (company_id)
  VALUES (new_company_id);

  RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."rls_auto_enable"() RETURNS "event_trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'pg_catalog'
    AS $$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$$;


ALTER FUNCTION "public"."rls_auto_enable"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."update_updated_at"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."update_updated_at"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."aa_licenses" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "company_id" "uuid" NOT NULL,
    "license_no" "text" NOT NULL,
    "issue_date" "date" NOT NULL,
    "validity_date" "date" NOT NULL,
    "hs_codes" "text"[],
    "import_obligation" numeric(18,2),
    "export_obligation" numeric(18,2),
    "import_fulfilled" numeric(18,2) DEFAULT 0 NOT NULL,
    "export_fulfilled" numeric(18,2) DEFAULT 0 NOT NULL,
    "status" "text" DEFAULT 'active'::"text" NOT NULL,
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "aa_licenses_status_check" CHECK (("status" = ANY (ARRAY['active'::"text", 'fulfilled'::"text", 'expired'::"text", 'surrendered'::"text"])))
);


ALTER TABLE "public"."aa_licenses" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."api_keys" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "company_id" "uuid" NOT NULL,
    "key_hash" "text" NOT NULL,
    "name" "text" NOT NULL,
    "permissions" "text"[] DEFAULT '{read}'::"text"[] NOT NULL,
    "rate_limit" integer DEFAULT 1000 NOT NULL,
    "last_used_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "revoked_at" timestamp with time zone
);


ALTER TABLE "public"."api_keys" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."audit_log" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "company_id" "uuid",
    "user_id" "uuid",
    "action" "text" NOT NULL,
    "entity_type" "text",
    "entity_id" "text",
    "details" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."audit_log" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."brc_firc_records" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "company_id" "uuid" NOT NULL,
    "shipment_id" "uuid",
    "document_type" "text" DEFAULT 'brc'::"text" NOT NULL,
    "document_no" "text",
    "invoice_no" "text",
    "invoice_date" "date",
    "invoice_amount" numeric(18,2) NOT NULL,
    "invoice_currency" "text" DEFAULT 'USD'::"text" NOT NULL,
    "realized_amount" numeric(18,2),
    "realized_currency" "text" DEFAULT 'INR'::"text",
    "realization_date" "date",
    "bank_name" "text",
    "ad_code" "text",
    "status" "text" DEFAULT 'pending'::"text" NOT NULL,
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "brc_firc_records_document_type_check" CHECK (("document_type" = ANY (ARRAY['brc'::"text", 'firc'::"text"]))),
    CONSTRAINT "brc_firc_records_status_check" CHECK (("status" = ANY (ARRAY['pending'::"text", 'partial'::"text", 'realized'::"text", 'overdue'::"text"])))
);


ALTER TABLE "public"."brc_firc_records" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."ca_relationships" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "ca_company_id" "uuid" NOT NULL,
    "client_company_id" "uuid" NOT NULL,
    "client_label" "text",
    "added_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."ca_relationships" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."cbam_leads" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "email" "text" NOT NULL,
    "company" "text",
    "hs_codes" "text"[],
    "any_in_scope" boolean,
    "sectors" "text"[],
    "source" "text" DEFAULT 'cbam-checker'::"text",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."cbam_leads" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."certifications" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "country_code" "text" NOT NULL,
    "product_category" "text" NOT NULL,
    "cert_list" "text"[] DEFAULT '{}'::"text"[] NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."certifications" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."checklist_progress" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "company_id" "uuid" NOT NULL,
    "shipment_id" "uuid",
    "country_code" "text" NOT NULL,
    "product" "text" NOT NULL,
    "checked_items" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."checklist_progress" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."companies" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "name" "text" DEFAULT 'My Company'::"text" NOT NULL,
    "size" "text" DEFAULT 'small'::"text" NOT NULL,
    "iec" "text",
    "plan" "text" DEFAULT 'free'::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "city" "text",
    "state" "text",
    "pin" integer,
    "state_code" "text",
    "port_of_loading" "text",
    "gstin" "text",
    "address" "text",
    "designation" "text",
    "whatsapp" "text",
    "turnover_range" "text",
    "years_exporting" "text",
    "known_regulations" "text"[],
    "compliance_confidence" integer,
    "past_compliance_issues" "text"[],
    "pain_points" "text"[],
    "whatsapp_number" "text",
    "whatsapp_alerts" boolean DEFAULT false NOT NULL,
    "onboarded_at" timestamp with time zone,
    "trade_role" "text",
    "recovery_digest" boolean DEFAULT true NOT NULL,
    CONSTRAINT "companies_plan_check" CHECK (("plan" = ANY (ARRAY['free'::"text", 'growth'::"text", 'enterprise'::"text"]))),
    CONSTRAINT "companies_size_check" CHECK (("size" = ANY (ARRAY['micro'::"text", 'small'::"text", 'medium'::"text", 'large'::"text"]))),
    CONSTRAINT "companies_trade_role_check" CHECK (("trade_role" = ANY (ARRAY['exporter'::"text", 'importer'::"text", 'both'::"text"])))
);


ALTER TABLE "public"."companies" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."compliance_gates" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "shipment_id" "uuid" NOT NULL,
    "company_id" "uuid" NOT NULL,
    "hs_validation" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "fta_eligibility" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "coo_requirement" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "rules_of_origin" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "checklist_progress" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "gate_status" "text" DEFAULT 'pending'::"text" NOT NULL,
    "blocking_reasons" "text"[] DEFAULT '{}'::"text"[] NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "compliance_gates_gate_status_check" CHECK (("gate_status" = ANY (ARRAY['pending'::"text", 'approved'::"text", 'blocked'::"text"])))
);


ALTER TABLE "public"."compliance_gates" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."countries" (
    "code" "text" NOT NULL,
    "name" "text" NOT NULL,
    "flag" "text" NOT NULL,
    "cbam_config" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "esg_config" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "packaging" "text"[] DEFAULT '{}'::"text"[] NOT NULL,
    "labeling" "text"[] DEFAULT '{}'::"text"[] NOT NULL,
    "customs" "text"[] DEFAULT '{}'::"text"[] NOT NULL,
    "sanctions" "text"[] DEFAULT '{}'::"text"[] NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."countries" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."epcg_licenses" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "company_id" "uuid" NOT NULL,
    "license_no" "text" NOT NULL,
    "issue_date" "date" NOT NULL,
    "validity_date" "date" NOT NULL,
    "duty_saved" numeric(18,2) NOT NULL,
    "export_obligation" numeric(18,2) NOT NULL,
    "export_fulfilled" numeric(18,2) DEFAULT 0 NOT NULL,
    "obligation_period_years" integer DEFAULT 6 NOT NULL,
    "status" "text" DEFAULT 'active'::"text" NOT NULL,
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "epcg_licenses_status_check" CHECK (("status" = ANY (ARRAY['active'::"text", 'fulfilled'::"text", 'defaulted'::"text", 'extended'::"text"])))
);


ALTER TABLE "public"."epcg_licenses" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."export_schemes" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "name" "text" NOT NULL,
    "description" "text" NOT NULL,
    "status" "text" NOT NULL,
    "details" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "source_url" "text",
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."export_schemes" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."fta_agreements" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "country_code" "text" NOT NULL,
    "name" "text" NOT NULL,
    "status" "text" NOT NULL,
    "effective_date" "date",
    "round" "text",
    "preferential_tariff" boolean DEFAULT false NOT NULL,
    "notes" "text",
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "fta_agreements_status_check" CHECK (("status" = ANY (ARRAY['Active'::"text", 'Under Negotiation'::"text", 'No FTA'::"text"])))
);


ALTER TABLE "public"."fta_agreements" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."hs_codes" (
    "code" "text" NOT NULL,
    "chapter" "text" NOT NULL,
    "description" "text" NOT NULL,
    "product_category" "text",
    "export_policy" "text" DEFAULT 'Free'::"text",
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."hs_codes" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."hs_tariff_rates" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "hs_code" "text" NOT NULL,
    "hs_description" "text",
    "country_code" "text" NOT NULL,
    "agreement" "text",
    "mfn_rate" numeric(6,2) NOT NULL,
    "preferential_rate" numeric(6,2) NOT NULL,
    "rule_of_origin" "text",
    "product_category" "text",
    "source" "text",
    "scraped_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."hs_tariff_rates" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."igst_claims" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "company_id" "uuid" NOT NULL,
    "shipment_id" "uuid",
    "shipping_bill_no" "text" NOT NULL,
    "shipping_bill_date" "date" NOT NULL,
    "port_code" "text",
    "hs_code" "text",
    "invoice_value" numeric(18,2) NOT NULL,
    "igst_paid" numeric(18,2) NOT NULL,
    "arn_no" "text",
    "refund_status" "text" DEFAULT 'filed'::"text" NOT NULL,
    "refund_amount" numeric(18,2),
    "credited_date" "date",
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "igst_claims_refund_status_check" CHECK (("refund_status" = ANY (ARRAY['filed'::"text", 'under_processing'::"text", 'sanctioned'::"text", 'credited'::"text", 'deficiency_memo'::"text"])))
);


ALTER TABLE "public"."igst_claims" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."product_categories" (
    "id" "text" NOT NULL,
    "label" "text" NOT NULL,
    "icon" "text" NOT NULL,
    "hs_prefix" "text"[] DEFAULT '{}'::"text"[] NOT NULL
);


ALTER TABLE "public"."product_categories" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."rate_limits" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "fn_name" "text" NOT NULL,
    "window_date" "date" DEFAULT CURRENT_DATE NOT NULL,
    "count" integer DEFAULT 1 NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."rate_limits" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."regulatory_changes" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "country_code" "text" NOT NULL,
    "date" "text" NOT NULL,
    "change_description" "text" NOT NULL,
    "source_url" "text",
    "severity" "text" DEFAULT 'info'::"text" NOT NULL,
    "scraped_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" "text",
    "alert_type" "text" DEFAULT 'regulation_change'::"text" NOT NULL,
    "source_name" "text",
    "external_id" "text",
    "product_tags" "text"[] DEFAULT '{}'::"text"[] NOT NULL,
    "country_name" "text",
    "flag" "text",
    CONSTRAINT "regulatory_changes_alert_type_check" CHECK (("alert_type" = ANY (ARRAY['deadline'::"text", 'regulation_change'::"text", 'fta_update'::"text", 'info'::"text"]))),
    CONSTRAINT "regulatory_changes_severity_check" CHECK (("severity" = ANY (ARRAY['critical'::"text", 'warning'::"text", 'info'::"text"])))
);


ALTER TABLE "public"."regulatory_changes" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."rodtep_rates" (
    "hs_code" "text" NOT NULL,
    "rate" numeric(6,4) NOT NULL,
    "notified_at" "text",
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."rodtep_rates" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."sanctions_aliases" (
    "id" integer NOT NULL,
    "uid" "text" NOT NULL,
    "alias" "text" NOT NULL,
    "alias_norm" "text" NOT NULL,
    "alias_type" "text"
);


ALTER TABLE "public"."sanctions_aliases" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."sanctions_aliases_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."sanctions_aliases_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."sanctions_aliases_id_seq" OWNED BY "public"."sanctions_aliases"."id";



CREATE TABLE IF NOT EXISTS "public"."sanctions_entries" (
    "uid" "text" NOT NULL,
    "name" "text" NOT NULL,
    "name_norm" "text" NOT NULL,
    "entity_type" "text",
    "program" "text",
    "remarks" "text",
    "source" "text" DEFAULT 'OFAC SDN'::"text" NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."sanctions_entries" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."shipments" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "company_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "product" "text" NOT NULL,
    "country" "text" NOT NULL,
    "date" "date" NOT NULL,
    "status" "text" DEFAULT 'pending'::"text" NOT NULL,
    "risk_score" integer,
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "hs_code" "text",
    "shipment_value" numeric(14,2),
    "gate_status" "text" DEFAULT 'pending'::"text",
    "buyer_name" "text",
    "sanctions_risk" "text",
    "value_currency" "text" DEFAULT 'USD'::"text",
    "shipping_bill_no" "text",
    "rodtep_rate" numeric(6,4),
    "rodtep_claimed" boolean DEFAULT false,
    "rodtep_claim_date" "date",
    "rodtep_match_type" "text",
    "rodtep_claim_status" "text" DEFAULT 'unclaimed'::"text" NOT NULL,
    "rodtep_claim_note" "text",
    CONSTRAINT "shipments_gate_status_check" CHECK (("gate_status" = ANY (ARRAY['pending'::"text", 'approved'::"text", 'blocked'::"text"]))),
    CONSTRAINT "shipments_rodtep_claim_status_check" CHECK (("rodtep_claim_status" = ANY (ARRAY['unclaimed'::"text", 'filed'::"text", 'credited'::"text", 'rejected'::"text"]))),
    CONSTRAINT "shipments_rodtep_match_type_check" CHECK (("rodtep_match_type" = ANY (ARRAY['exact'::"text", 'prefix'::"text", 'default'::"text"]))),
    CONSTRAINT "shipments_sanctions_risk_check" CHECK (("sanctions_risk" = ANY (ARRAY['clear'::"text", 'flag'::"text", 'block'::"text"]))),
    CONSTRAINT "shipments_status_check" CHECK (("status" = ANY (ARRAY['pending'::"text", 'preparing'::"text", 'in_progress'::"text", 'in_transit'::"text", 'delivered'::"text"])))
);


ALTER TABLE "public"."shipments" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."user_profiles" (
    "id" "uuid" NOT NULL,
    "company_id" "uuid" NOT NULL,
    "email" "text" NOT NULL,
    "full_name" "text",
    "role" "text" DEFAULT 'owner'::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "user_profiles_role_check" CHECK (("role" = ANY (ARRAY['owner'::"text", 'admin'::"text", 'viewer'::"text"])))
);


ALTER TABLE "public"."user_profiles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."user_settings" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "company_id" "uuid" NOT NULL,
    "selected_product" "text" DEFAULT 'steel'::"text" NOT NULL,
    "selected_countries" "text"[] DEFAULT '{EU,UAE}'::"text"[] NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."user_settings" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."whatsapp_alert_log" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "company_id" "uuid" NOT NULL,
    "alert_key" "text" NOT NULL,
    "sent_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "phone_to" "text" NOT NULL
);


ALTER TABLE "public"."whatsapp_alert_log" OWNER TO "postgres";


ALTER TABLE ONLY "public"."sanctions_aliases" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."sanctions_aliases_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."aa_licenses"
    ADD CONSTRAINT "aa_licenses_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."api_keys"
    ADD CONSTRAINT "api_keys_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."audit_log"
    ADD CONSTRAINT "audit_log_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."brc_firc_records"
    ADD CONSTRAINT "brc_firc_records_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ca_relationships"
    ADD CONSTRAINT "ca_relationships_ca_company_id_client_company_id_key" UNIQUE ("ca_company_id", "client_company_id");



ALTER TABLE ONLY "public"."ca_relationships"
    ADD CONSTRAINT "ca_relationships_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."cbam_leads"
    ADD CONSTRAINT "cbam_leads_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."certifications"
    ADD CONSTRAINT "certifications_country_code_product_category_key" UNIQUE ("country_code", "product_category");



ALTER TABLE ONLY "public"."certifications"
    ADD CONSTRAINT "certifications_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."checklist_progress"
    ADD CONSTRAINT "checklist_progress_company_id_shipment_id_country_code_key" UNIQUE ("company_id", "shipment_id", "country_code");



ALTER TABLE ONLY "public"."checklist_progress"
    ADD CONSTRAINT "checklist_progress_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."companies"
    ADD CONSTRAINT "companies_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."compliance_gates"
    ADD CONSTRAINT "compliance_gates_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."compliance_gates"
    ADD CONSTRAINT "compliance_gates_shipment_id_key" UNIQUE ("shipment_id");



ALTER TABLE ONLY "public"."countries"
    ADD CONSTRAINT "countries_pkey" PRIMARY KEY ("code");



ALTER TABLE ONLY "public"."epcg_licenses"
    ADD CONSTRAINT "epcg_licenses_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."export_schemes"
    ADD CONSTRAINT "export_schemes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."fta_agreements"
    ADD CONSTRAINT "fta_agreements_country_code_key" UNIQUE ("country_code");



ALTER TABLE ONLY "public"."fta_agreements"
    ADD CONSTRAINT "fta_agreements_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."hs_codes"
    ADD CONSTRAINT "hs_codes_pkey" PRIMARY KEY ("code");



ALTER TABLE ONLY "public"."hs_tariff_rates"
    ADD CONSTRAINT "hs_tariff_rates_hs_code_country_code_agreement_key" UNIQUE ("hs_code", "country_code", "agreement");



ALTER TABLE ONLY "public"."hs_tariff_rates"
    ADD CONSTRAINT "hs_tariff_rates_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."igst_claims"
    ADD CONSTRAINT "igst_claims_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."product_categories"
    ADD CONSTRAINT "product_categories_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rate_limits"
    ADD CONSTRAINT "rate_limits_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rate_limits"
    ADD CONSTRAINT "rate_limits_user_id_fn_name_window_date_key" UNIQUE ("user_id", "fn_name", "window_date");



ALTER TABLE ONLY "public"."regulatory_changes"
    ADD CONSTRAINT "regulatory_changes_external_id_key" UNIQUE ("external_id");



ALTER TABLE ONLY "public"."regulatory_changes"
    ADD CONSTRAINT "regulatory_changes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rodtep_rates"
    ADD CONSTRAINT "rodtep_rates_pkey" PRIMARY KEY ("hs_code");



ALTER TABLE ONLY "public"."sanctions_aliases"
    ADD CONSTRAINT "sanctions_aliases_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."sanctions_entries"
    ADD CONSTRAINT "sanctions_entries_pkey" PRIMARY KEY ("uid");



ALTER TABLE ONLY "public"."shipments"
    ADD CONSTRAINT "shipments_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_profiles"
    ADD CONSTRAINT "user_profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_settings"
    ADD CONSTRAINT "user_settings_company_id_key" UNIQUE ("company_id");



ALTER TABLE ONLY "public"."user_settings"
    ADD CONSTRAINT "user_settings_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."whatsapp_alert_log"
    ADD CONSTRAINT "whatsapp_alert_log_company_id_alert_key_key" UNIQUE ("company_id", "alert_key");



ALTER TABLE ONLY "public"."whatsapp_alert_log"
    ADD CONSTRAINT "whatsapp_alert_log_pkey" PRIMARY KEY ("id");



CREATE INDEX "hs_codes_code_prefix" ON "public"."hs_codes" USING "btree" ("code" "text_pattern_ops");



CREATE INDEX "hs_codes_description_fts" ON "public"."hs_codes" USING "gin" ("to_tsvector"('"english"'::"regconfig", "description"));



CREATE INDEX "idx_aa_licenses_company" ON "public"."aa_licenses" USING "btree" ("company_id");



CREATE INDEX "idx_audit_log_company" ON "public"."audit_log" USING "btree" ("company_id");



CREATE INDEX "idx_brc_firc_company" ON "public"."brc_firc_records" USING "btree" ("company_id");



CREATE INDEX "idx_brc_firc_status" ON "public"."brc_firc_records" USING "btree" ("company_id", "status");



CREATE INDEX "idx_ca_relationships_ca" ON "public"."ca_relationships" USING "btree" ("ca_company_id");



CREATE INDEX "idx_ca_relationships_client" ON "public"."ca_relationships" USING "btree" ("client_company_id");



CREATE INDEX "idx_cbam_leads_created" ON "public"."cbam_leads" USING "btree" ("created_at" DESC);



CREATE INDEX "idx_cbam_leads_email" ON "public"."cbam_leads" USING "btree" ("email");



CREATE INDEX "idx_certifications_country" ON "public"."certifications" USING "btree" ("country_code");



CREATE INDEX "idx_checklist_company" ON "public"."checklist_progress" USING "btree" ("company_id");



CREATE INDEX "idx_checklist_shipment" ON "public"."checklist_progress" USING "btree" ("shipment_id");



CREATE INDEX "idx_compliance_gates_company" ON "public"."compliance_gates" USING "btree" ("company_id");



CREATE INDEX "idx_compliance_gates_shipment" ON "public"."compliance_gates" USING "btree" ("shipment_id");



CREATE INDEX "idx_epcg_licenses_company" ON "public"."epcg_licenses" USING "btree" ("company_id");



CREATE INDEX "idx_hs_tariff_code" ON "public"."hs_tariff_rates" USING "btree" ("hs_code");



CREATE INDEX "idx_hs_tariff_country" ON "public"."hs_tariff_rates" USING "btree" ("country_code");



CREATE INDEX "idx_igst_claims_company" ON "public"."igst_claims" USING "btree" ("company_id");



CREATE INDEX "idx_igst_claims_status" ON "public"."igst_claims" USING "btree" ("company_id", "refund_status");



CREATE INDEX "idx_rate_limits_lookup" ON "public"."rate_limits" USING "btree" ("user_id", "fn_name", "window_date");



CREATE INDEX "idx_regulatory_changes_country" ON "public"."regulatory_changes" USING "btree" ("country_code");



CREATE INDEX "idx_regulatory_changes_date" ON "public"."regulatory_changes" USING "btree" ("scraped_at" DESC);



CREATE INDEX "idx_rodtep_hs6" ON "public"."rodtep_rates" USING "btree" ("left"("hs_code", 6));



CREATE INDEX "idx_sanctions_aliases_fts" ON "public"."sanctions_aliases" USING "gin" ("to_tsvector"('"simple"'::"regconfig", "alias_norm"));



CREATE INDEX "idx_sanctions_aliases_norm" ON "public"."sanctions_aliases" USING "btree" ("alias_norm");



CREATE INDEX "idx_sanctions_entries_fts" ON "public"."sanctions_entries" USING "gin" ("to_tsvector"('"simple"'::"regconfig", "name_norm"));



CREATE INDEX "idx_sanctions_entries_name" ON "public"."sanctions_entries" USING "btree" ("name_norm");



CREATE INDEX "idx_shipments_company" ON "public"."shipments" USING "btree" ("company_id");



CREATE INDEX "idx_shipments_gate_status" ON "public"."shipments" USING "btree" ("gate_status");



CREATE INDEX "idx_shipments_hs_code" ON "public"."shipments" USING "btree" ("hs_code") WHERE ("hs_code" IS NOT NULL);



CREATE INDEX "idx_shipments_rodtep_claim_status" ON "public"."shipments" USING "btree" ("company_id", "rodtep_claim_status") WHERE (("hs_code" IS NOT NULL) AND ("shipment_value" IS NOT NULL));



CREATE INDEX "idx_shipments_rodtep_unclaimed" ON "public"."shipments" USING "btree" ("company_id", "rodtep_claimed") WHERE (("rodtep_claimed" = false) AND ("hs_code" IS NOT NULL) AND ("shipment_value" IS NOT NULL));



CREATE INDEX "idx_shipments_sanctions" ON "public"."shipments" USING "btree" ("sanctions_risk") WHERE ("sanctions_risk" = ANY (ARRAY['flag'::"text", 'block'::"text"]));



CREATE INDEX "idx_shipments_status" ON "public"."shipments" USING "btree" ("status");



CREATE INDEX "idx_whatsapp_log_company" ON "public"."whatsapp_alert_log" USING "btree" ("company_id");



CREATE OR REPLACE TRIGGER "set_checklist_updated_at" BEFORE UPDATE ON "public"."checklist_progress" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();



CREATE OR REPLACE TRIGGER "set_companies_updated_at" BEFORE UPDATE ON "public"."companies" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();



CREATE OR REPLACE TRIGGER "set_compliance_gates_updated_at" BEFORE UPDATE ON "public"."compliance_gates" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();



CREATE OR REPLACE TRIGGER "set_settings_updated_at" BEFORE UPDATE ON "public"."user_settings" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();



CREATE OR REPLACE TRIGGER "set_shipments_updated_at" BEFORE UPDATE ON "public"."shipments" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();



ALTER TABLE ONLY "public"."aa_licenses"
    ADD CONSTRAINT "aa_licenses_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."api_keys"
    ADD CONSTRAINT "api_keys_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."audit_log"
    ADD CONSTRAINT "audit_log_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."audit_log"
    ADD CONSTRAINT "audit_log_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."brc_firc_records"
    ADD CONSTRAINT "brc_firc_records_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."brc_firc_records"
    ADD CONSTRAINT "brc_firc_records_shipment_id_fkey" FOREIGN KEY ("shipment_id") REFERENCES "public"."shipments"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."ca_relationships"
    ADD CONSTRAINT "ca_relationships_ca_company_id_fkey" FOREIGN KEY ("ca_company_id") REFERENCES "public"."companies"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."ca_relationships"
    ADD CONSTRAINT "ca_relationships_client_company_id_fkey" FOREIGN KEY ("client_company_id") REFERENCES "public"."companies"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."certifications"
    ADD CONSTRAINT "certifications_country_code_fkey" FOREIGN KEY ("country_code") REFERENCES "public"."countries"("code") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."checklist_progress"
    ADD CONSTRAINT "checklist_progress_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."checklist_progress"
    ADD CONSTRAINT "checklist_progress_shipment_id_fkey" FOREIGN KEY ("shipment_id") REFERENCES "public"."shipments"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."compliance_gates"
    ADD CONSTRAINT "compliance_gates_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."compliance_gates"
    ADD CONSTRAINT "compliance_gates_shipment_id_fkey" FOREIGN KEY ("shipment_id") REFERENCES "public"."shipments"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."epcg_licenses"
    ADD CONSTRAINT "epcg_licenses_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."fta_agreements"
    ADD CONSTRAINT "fta_agreements_country_code_fkey" FOREIGN KEY ("country_code") REFERENCES "public"."countries"("code") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."hs_tariff_rates"
    ADD CONSTRAINT "hs_tariff_rates_country_code_fkey" FOREIGN KEY ("country_code") REFERENCES "public"."countries"("code") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."igst_claims"
    ADD CONSTRAINT "igst_claims_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."igst_claims"
    ADD CONSTRAINT "igst_claims_shipment_id_fkey" FOREIGN KEY ("shipment_id") REFERENCES "public"."shipments"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."rate_limits"
    ADD CONSTRAINT "rate_limits_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."regulatory_changes"
    ADD CONSTRAINT "regulatory_changes_country_code_fkey" FOREIGN KEY ("country_code") REFERENCES "public"."countries"("code") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."sanctions_aliases"
    ADD CONSTRAINT "sanctions_aliases_uid_fkey" FOREIGN KEY ("uid") REFERENCES "public"."sanctions_entries"("uid") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."shipments"
    ADD CONSTRAINT "shipments_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_profiles"
    ADD CONSTRAINT "user_profiles_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_profiles"
    ADD CONSTRAINT "user_profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_settings"
    ADD CONSTRAINT "user_settings_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."whatsapp_alert_log"
    ADD CONSTRAINT "whatsapp_alert_log_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE CASCADE;



CREATE POLICY "Allow authenticated read on rodtep_rates" ON "public"."rodtep_rates" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Allow authenticated read on sanctions_aliases" ON "public"."sanctions_aliases" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Allow authenticated read on sanctions_entries" ON "public"."sanctions_entries" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Allow authenticated users to read regulatory changes" ON "public"."regulatory_changes" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Anon can submit CBAM leads" ON "public"."cbam_leads" FOR INSERT TO "anon" WITH CHECK (true);



CREATE POLICY "Authenticated can read cbam_leads" ON "public"."cbam_leads" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Service role full access on cbam_leads" ON "public"."cbam_leads" TO "service_role" USING (true) WITH CHECK (true);



CREATE POLICY "Service role full access on rodtep_rates" ON "public"."rodtep_rates" TO "service_role" USING (true) WITH CHECK (true);



CREATE POLICY "Service role full access on sanctions_aliases" ON "public"."sanctions_aliases" TO "service_role" USING (true) WITH CHECK (true);



CREATE POLICY "Service role full access on sanctions_entries" ON "public"."sanctions_entries" TO "service_role" USING (true) WITH CHECK (true);



CREATE POLICY "Users manage own alert log" ON "public"."whatsapp_alert_log" USING (("company_id" IN ( SELECT "user_profiles"."company_id"
   FROM "public"."user_profiles"
  WHERE ("user_profiles"."id" = "auth"."uid"()))));



ALTER TABLE "public"."aa_licenses" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."api_keys" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."audit_log" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."brc_firc_records" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "ca_can_manage_own_relationships" ON "public"."ca_relationships" USING (("ca_company_id" IN ( SELECT "user_profiles"."company_id"
   FROM "public"."user_profiles"
  WHERE ("user_profiles"."id" = "auth"."uid"()))));



CREATE POLICY "ca_can_read_client_companies" ON "public"."companies" FOR SELECT USING (("id" IN ( SELECT "ca_relationships"."client_company_id"
   FROM "public"."ca_relationships"
  WHERE ("ca_relationships"."ca_company_id" IN ( SELECT "user_profiles"."company_id"
           FROM "public"."user_profiles"
          WHERE ("user_profiles"."id" = "auth"."uid"()))))));



CREATE POLICY "ca_can_read_client_shipments" ON "public"."shipments" FOR SELECT USING (("company_id" IN ( SELECT "ca_relationships"."client_company_id"
   FROM "public"."ca_relationships"
  WHERE ("ca_relationships"."ca_company_id" IN ( SELECT "user_profiles"."company_id"
           FROM "public"."user_profiles"
          WHERE ("user_profiles"."id" = "auth"."uid"()))))));



ALTER TABLE "public"."ca_relationships" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."cbam_leads" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."certifications" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."checklist_progress" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."companies" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "companies_own_select" ON "public"."companies" FOR SELECT TO "authenticated" USING (("id" = "public"."get_user_company_id"()));



CREATE POLICY "companies_own_update" ON "public"."companies" FOR UPDATE TO "authenticated" USING (("id" = "public"."get_user_company_id"())) WITH CHECK (("id" = "public"."get_user_company_id"()));



CREATE POLICY "company_aa_licenses" ON "public"."aa_licenses" USING (("company_id" IN ( SELECT "user_profiles"."company_id"
   FROM "public"."user_profiles"
  WHERE ("user_profiles"."id" = "auth"."uid"()))));



CREATE POLICY "company_apikeys_all" ON "public"."api_keys" USING (("company_id" = "public"."get_user_company_id"()));



CREATE POLICY "company_audit_insert" ON "public"."audit_log" FOR INSERT WITH CHECK (("company_id" = "public"."get_user_company_id"()));



CREATE POLICY "company_audit_select" ON "public"."audit_log" FOR SELECT USING (("company_id" = "public"."get_user_company_id"()));



CREATE POLICY "company_brc_firc_records" ON "public"."brc_firc_records" USING (("company_id" IN ( SELECT "user_profiles"."company_id"
   FROM "public"."user_profiles"
  WHERE ("user_profiles"."id" = "auth"."uid"()))));



CREATE POLICY "company_checklist_delete" ON "public"."checklist_progress" FOR DELETE USING (("company_id" = "public"."get_user_company_id"()));



CREATE POLICY "company_checklist_insert" ON "public"."checklist_progress" FOR INSERT WITH CHECK (("company_id" = "public"."get_user_company_id"()));



CREATE POLICY "company_checklist_select" ON "public"."checklist_progress" FOR SELECT USING (("company_id" = "public"."get_user_company_id"()));



CREATE POLICY "company_checklist_update" ON "public"."checklist_progress" FOR UPDATE USING (("company_id" = "public"."get_user_company_id"()));



CREATE POLICY "company_epcg_licenses" ON "public"."epcg_licenses" USING (("company_id" IN ( SELECT "user_profiles"."company_id"
   FROM "public"."user_profiles"
  WHERE ("user_profiles"."id" = "auth"."uid"()))));



CREATE POLICY "company_gates_delete" ON "public"."compliance_gates" FOR DELETE USING (("company_id" = "public"."get_user_company_id"()));



CREATE POLICY "company_gates_insert" ON "public"."compliance_gates" FOR INSERT WITH CHECK (("company_id" = "public"."get_user_company_id"()));



CREATE POLICY "company_gates_select" ON "public"."compliance_gates" FOR SELECT USING (("company_id" = "public"."get_user_company_id"()));



CREATE POLICY "company_gates_update" ON "public"."compliance_gates" FOR UPDATE USING (("company_id" = "public"."get_user_company_id"()));



CREATE POLICY "company_igst_claims" ON "public"."igst_claims" USING (("company_id" IN ( SELECT "user_profiles"."company_id"
   FROM "public"."user_profiles"
  WHERE ("user_profiles"."id" = "auth"."uid"()))));



CREATE POLICY "company_settings_insert" ON "public"."user_settings" FOR INSERT WITH CHECK (("company_id" = "public"."get_user_company_id"()));



CREATE POLICY "company_settings_select" ON "public"."user_settings" FOR SELECT USING (("company_id" = "public"."get_user_company_id"()));



CREATE POLICY "company_settings_update" ON "public"."user_settings" FOR UPDATE USING (("company_id" = "public"."get_user_company_id"()));



CREATE POLICY "company_shipments_delete" ON "public"."shipments" FOR DELETE USING (("company_id" = "public"."get_user_company_id"()));



CREATE POLICY "company_shipments_insert" ON "public"."shipments" FOR INSERT WITH CHECK (("company_id" = "public"."get_user_company_id"()));



CREATE POLICY "company_shipments_select" ON "public"."shipments" FOR SELECT USING (("company_id" = "public"."get_user_company_id"()));



CREATE POLICY "company_shipments_update" ON "public"."shipments" FOR UPDATE USING (("company_id" = "public"."get_user_company_id"()));



ALTER TABLE "public"."compliance_gates" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."countries" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."epcg_licenses" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."export_schemes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."fta_agreements" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."hs_codes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."hs_tariff_rates" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "hs_tariff_rates_read" ON "public"."hs_tariff_rates" FOR SELECT TO "authenticated" USING (true);



ALTER TABLE "public"."igst_claims" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."product_categories" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."rate_limits" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "rate_limits_self" ON "public"."rate_limits" USING (("user_id" = "auth"."uid"()));



CREATE POLICY "rate_limits_service" ON "public"."rate_limits" TO "service_role" USING (true) WITH CHECK (true);



ALTER TABLE "public"."regulatory_changes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."rodtep_rates" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."sanctions_aliases" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."sanctions_entries" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."shipments" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_profiles" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "user_profiles_self_select" ON "public"."user_profiles" FOR SELECT TO "authenticated" USING (("id" = "auth"."uid"()));



ALTER TABLE "public"."user_settings" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."whatsapp_alert_log" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON FUNCTION "public"."cleanup_rate_limits"() TO "anon";
GRANT ALL ON FUNCTION "public"."cleanup_rate_limits"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."cleanup_rate_limits"() TO "service_role";



GRANT ALL ON FUNCTION "public"."get_user_company_id"() TO "anon";
GRANT ALL ON FUNCTION "public"."get_user_company_id"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_user_company_id"() TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";



GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "anon";
GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "service_role";



GRANT ALL ON FUNCTION "public"."update_updated_at"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_updated_at"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_updated_at"() TO "service_role";



GRANT ALL ON TABLE "public"."aa_licenses" TO "anon";
GRANT ALL ON TABLE "public"."aa_licenses" TO "authenticated";
GRANT ALL ON TABLE "public"."aa_licenses" TO "service_role";



GRANT ALL ON TABLE "public"."api_keys" TO "anon";
GRANT ALL ON TABLE "public"."api_keys" TO "authenticated";
GRANT ALL ON TABLE "public"."api_keys" TO "service_role";



GRANT ALL ON TABLE "public"."audit_log" TO "anon";
GRANT ALL ON TABLE "public"."audit_log" TO "authenticated";
GRANT ALL ON TABLE "public"."audit_log" TO "service_role";



GRANT ALL ON TABLE "public"."brc_firc_records" TO "anon";
GRANT ALL ON TABLE "public"."brc_firc_records" TO "authenticated";
GRANT ALL ON TABLE "public"."brc_firc_records" TO "service_role";



GRANT ALL ON TABLE "public"."ca_relationships" TO "anon";
GRANT ALL ON TABLE "public"."ca_relationships" TO "authenticated";
GRANT ALL ON TABLE "public"."ca_relationships" TO "service_role";



GRANT ALL ON TABLE "public"."cbam_leads" TO "anon";
GRANT ALL ON TABLE "public"."cbam_leads" TO "authenticated";
GRANT ALL ON TABLE "public"."cbam_leads" TO "service_role";



GRANT ALL ON TABLE "public"."certifications" TO "anon";
GRANT ALL ON TABLE "public"."certifications" TO "authenticated";
GRANT ALL ON TABLE "public"."certifications" TO "service_role";



GRANT ALL ON TABLE "public"."checklist_progress" TO "anon";
GRANT ALL ON TABLE "public"."checklist_progress" TO "authenticated";
GRANT ALL ON TABLE "public"."checklist_progress" TO "service_role";



GRANT ALL ON TABLE "public"."companies" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."companies" TO "authenticated";
GRANT ALL ON TABLE "public"."companies" TO "service_role";



GRANT UPDATE("name") ON TABLE "public"."companies" TO "authenticated";



GRANT UPDATE("size") ON TABLE "public"."companies" TO "authenticated";



GRANT UPDATE("iec") ON TABLE "public"."companies" TO "authenticated";



GRANT UPDATE("city") ON TABLE "public"."companies" TO "authenticated";



GRANT UPDATE("state") ON TABLE "public"."companies" TO "authenticated";



GRANT UPDATE("pin") ON TABLE "public"."companies" TO "authenticated";



GRANT UPDATE("state_code") ON TABLE "public"."companies" TO "authenticated";



GRANT UPDATE("port_of_loading") ON TABLE "public"."companies" TO "authenticated";



GRANT UPDATE("gstin") ON TABLE "public"."companies" TO "authenticated";



GRANT UPDATE("address") ON TABLE "public"."companies" TO "authenticated";



GRANT UPDATE("designation") ON TABLE "public"."companies" TO "authenticated";



GRANT UPDATE("whatsapp") ON TABLE "public"."companies" TO "authenticated";



GRANT UPDATE("turnover_range") ON TABLE "public"."companies" TO "authenticated";



GRANT UPDATE("years_exporting") ON TABLE "public"."companies" TO "authenticated";



GRANT UPDATE("known_regulations") ON TABLE "public"."companies" TO "authenticated";



GRANT UPDATE("compliance_confidence") ON TABLE "public"."companies" TO "authenticated";



GRANT UPDATE("past_compliance_issues") ON TABLE "public"."companies" TO "authenticated";



GRANT UPDATE("pain_points") ON TABLE "public"."companies" TO "authenticated";



GRANT UPDATE("whatsapp_number") ON TABLE "public"."companies" TO "authenticated";



GRANT UPDATE("whatsapp_alerts") ON TABLE "public"."companies" TO "authenticated";



GRANT UPDATE("onboarded_at") ON TABLE "public"."companies" TO "authenticated";



GRANT UPDATE("trade_role") ON TABLE "public"."companies" TO "authenticated";



GRANT ALL ON TABLE "public"."compliance_gates" TO "anon";
GRANT ALL ON TABLE "public"."compliance_gates" TO "authenticated";
GRANT ALL ON TABLE "public"."compliance_gates" TO "service_role";



GRANT ALL ON TABLE "public"."countries" TO "anon";
GRANT ALL ON TABLE "public"."countries" TO "authenticated";
GRANT ALL ON TABLE "public"."countries" TO "service_role";



GRANT ALL ON TABLE "public"."epcg_licenses" TO "anon";
GRANT ALL ON TABLE "public"."epcg_licenses" TO "authenticated";
GRANT ALL ON TABLE "public"."epcg_licenses" TO "service_role";



GRANT ALL ON TABLE "public"."export_schemes" TO "anon";
GRANT ALL ON TABLE "public"."export_schemes" TO "authenticated";
GRANT ALL ON TABLE "public"."export_schemes" TO "service_role";



GRANT ALL ON TABLE "public"."fta_agreements" TO "anon";
GRANT ALL ON TABLE "public"."fta_agreements" TO "authenticated";
GRANT ALL ON TABLE "public"."fta_agreements" TO "service_role";



GRANT ALL ON TABLE "public"."hs_codes" TO "anon";
GRANT ALL ON TABLE "public"."hs_codes" TO "authenticated";
GRANT ALL ON TABLE "public"."hs_codes" TO "service_role";



GRANT ALL ON TABLE "public"."hs_tariff_rates" TO "anon";
GRANT ALL ON TABLE "public"."hs_tariff_rates" TO "authenticated";
GRANT ALL ON TABLE "public"."hs_tariff_rates" TO "service_role";



GRANT ALL ON TABLE "public"."igst_claims" TO "anon";
GRANT ALL ON TABLE "public"."igst_claims" TO "authenticated";
GRANT ALL ON TABLE "public"."igst_claims" TO "service_role";



GRANT ALL ON TABLE "public"."product_categories" TO "anon";
GRANT ALL ON TABLE "public"."product_categories" TO "authenticated";
GRANT ALL ON TABLE "public"."product_categories" TO "service_role";



GRANT ALL ON TABLE "public"."rate_limits" TO "anon";
GRANT ALL ON TABLE "public"."rate_limits" TO "authenticated";
GRANT ALL ON TABLE "public"."rate_limits" TO "service_role";



GRANT ALL ON TABLE "public"."regulatory_changes" TO "anon";
GRANT ALL ON TABLE "public"."regulatory_changes" TO "authenticated";
GRANT ALL ON TABLE "public"."regulatory_changes" TO "service_role";



GRANT ALL ON TABLE "public"."rodtep_rates" TO "anon";
GRANT ALL ON TABLE "public"."rodtep_rates" TO "authenticated";
GRANT ALL ON TABLE "public"."rodtep_rates" TO "service_role";



GRANT ALL ON TABLE "public"."sanctions_aliases" TO "anon";
GRANT ALL ON TABLE "public"."sanctions_aliases" TO "authenticated";
GRANT ALL ON TABLE "public"."sanctions_aliases" TO "service_role";



GRANT ALL ON SEQUENCE "public"."sanctions_aliases_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."sanctions_aliases_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."sanctions_aliases_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."sanctions_entries" TO "anon";
GRANT ALL ON TABLE "public"."sanctions_entries" TO "authenticated";
GRANT ALL ON TABLE "public"."sanctions_entries" TO "service_role";



GRANT ALL ON TABLE "public"."shipments" TO "anon";
GRANT ALL ON TABLE "public"."shipments" TO "authenticated";
GRANT ALL ON TABLE "public"."shipments" TO "service_role";



GRANT ALL ON TABLE "public"."user_profiles" TO "anon";
GRANT ALL ON TABLE "public"."user_profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."user_profiles" TO "service_role";



GRANT ALL ON TABLE "public"."user_settings" TO "anon";
GRANT ALL ON TABLE "public"."user_settings" TO "authenticated";
GRANT ALL ON TABLE "public"."user_settings" TO "service_role";



GRANT ALL ON TABLE "public"."whatsapp_alert_log" TO "anon";
GRANT ALL ON TABLE "public"."whatsapp_alert_log" TO "authenticated";
GRANT ALL ON TABLE "public"."whatsapp_alert_log" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";









-- ── Recovered from supabase/schema.sql: trigger on auth.users ──────────────
-- Not captured by a --schema public dump because the trigger lives on
-- auth.users. public.handle_new_user() is already defined above.

DROP TRIGGER IF EXISTS "on_auth_user_created" ON "auth"."users";

CREATE TRIGGER "on_auth_user_created"
  AFTER INSERT ON "auth"."users"
  FOR EACH ROW EXECUTE FUNCTION "public"."handle_new_user"();
